In [1]:
pip install PyGithub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyGithub in /Users/salvadorramirezjr/.local/lib/python3.8/site-packages (1.57)
Requirement already satisfied: deprecated in /Users/salvadorramirezjr/.local/lib/python3.8/site-packages (from PyGithub) (1.2.13)
Requirement already satisfied: pynacl>=1.4.0 in /Users/salvadorramirezjr/.local/lib/python3.8/site-packages (from PyGithub) (1.5.0)
Requirement already satisfied: requests>=2.14.0 in /opt/anaconda3/lib/python3.8/site-packages (from PyGithub) (2.25.1)
Requirement already satisfied: pyjwt>=2.4.0 in /Users/salvadorramirezjr/.local/lib/python3.8/site-packages (from PyGithub) (2.6.0)
Requirement already satisfied: cffi>=1.4.1 in /opt/anaconda3/lib/python3.8/site-packages (from pynacl>=1.4.0->PyGithub) (1.14.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (2.10)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/anaconda3/lib/python3.8/site-packages (from deprecated->PyGithub) (1.12.1)
Note: you may need to restart the kernel to use updated packages.

In [291]:
import time
import csv
import pandas as pd
import numpy as np
from github import Github

In [3]:
#input your own security token
token = ''
client = Github(token)

## Exploration of Org (ds-modules) and syntax

In [4]:
def search_github(keyword, query):
    '''
    keyword: what you want to search (query)
    query: https://docs.github.com/en/search-github/searching-on-github/searching-code#search-within-a-users-or-organizations-repositories
    '''
    rate_limit = client.get_rate_limit()
    rate = rate_limit.search
    if rate.remaining == 0:
        print(f'You have 0/{rate.limit} API calls remaining. Reset time: {rate.reset}')
        return
    else:
        print(f'You have {rate.remaining}/{rate.limit} API calls remaining')
     
    # to change query: add/remove parameters
    # useful extensions: md, ipynb, etc...
    # visit website linked in description
    print('Query: ' + keyword + ' ' + query)
    result = client.search_code(keyword + ' ' + query)
     
    max_size = 100
    print(f'Found {result.totalCount} file(s)')
    if result.totalCount > max_size:
        result = result[:max_size]
 
    for file in result:
        print(f'{file.download_url}')

In [296]:
search_github('Ari Edmundson', 'extension:ipynb org:ds-modules')

You have 30/30 API calls remaining
Query: Ari Edmundson extension:ipynb org:ds-modules
Found 1 file(s)
https://raw.githubusercontent.com/ds-modules/Search-Engine/332eb1b5f3021a0558463f27ccbda2a4b84b2c2e/Testing/Search_Repo_Test.ipynb

In [172]:
ds_modules = client.get_repo('ds-modules/ESPM-163ac')
contents = ds_modules.get_contents("")
for content_file in contents:
    print(content_file)

ContentFile(path=".DS_Store")
ContentFile(path="Lab1")
ContentFile(path="Lab2")
ContentFile(path="Lecture")
ContentFile(path="README.md")
ContentFile(path="data")
ContentFile(path="images")
ContentFile(path="requirements.txt")

In [323]:
modules_org = client.get_organization('ds-modules').get_repos()
repo_list = []
for i in modules_org:
    repo_list.append(i)
len(repo_list)

171

In [325]:
repo_list

[Repository(full_name="ds-modules/core-resources"),
 Repository(full_name="ds-modules/ENGIN-7"),
 Repository(full_name="ds-modules/DS-Modules"),
 Repository(full_name="ds-modules/ISF-189"),
 Repository(full_name="ds-modules/EDUC-223B"),
 Repository(full_name="ds-modules/NESTUD-190A"),
 Repository(full_name="ds-modules/ETHSTD-21AC"),
 Repository(full_name="ds-modules/XRHETOR-R1A"),
 Repository(full_name="ds-modules/HIST-88"),
 Repository(full_name="ds-modules/GWS-101"),
 Repository(full_name="ds-modules/ART-W23AC"),
 Repository(full_name="ds-modules/IAS-150"),
 Repository(full_name="ds-modules/SOC-130AC"),
 Repository(full_name="ds-modules/INFO-290"),
 Repository(full_name="ds-modules/Library-HTRC"),
 Repository(full_name="ds-modules/GWS-131"),
 Repository(full_name="ds-modules/LINGUIS-110"),
 Repository(full_name="ds-modules/PSYCH-167AC"),
 Repository(full_name="ds-modules/XENGLIS-31AC"),
 Repository(full_name="ds-modules/ECON-101B"),
 Repository(full_name="ds-modules/LS-88"),
 Repository(full_name="ds-modules/RDM-DeCal"),
 Repository(full_name="ds-modules/EPS-C20"),
 Repository(full_name="ds-modules/COGSCI-1B"),
 Repository(full_name="ds-modules/MCB-288"),
 Repository(full_name="ds-modules/SPORTS"),
 Repository(full_name="ds-modules/IB-ESPM-105"),
 Repository(full_name="ds-modules/ENVECON-100"),
 Repository(full_name="ds-modules/CUNEIF-102A"),
 Repository(full_name="ds-modules/Module-Feedback"),
 Repository(full_name="ds-modules/MEDST-250"),
 Repository(full_name="ds-modules/HIST-283"),
 Repository(full_name="ds-modules/LEGALST-190"),
 Repository(full_name="ds-modules/HTRC-Uncamp"),
 Repository(full_name="ds-modules/PACS-190"),
 Repository(full_name="ds-modules/examples"),
 Repository(full_name="ds-modules/R-Module"),
 Repository(full_name="ds-modules/IAS-106"),
 Repository(full_name="ds-modules/nbinteract-image"),
 Repository(full_name="ds-modules/PH-142"),
 Repository(full_name="ds-modules/E-157AC"),
 Repository(full_name="ds-modules/MCB-32"),
 Repository(full_name="ds-modules/HIST-160"),
 Repository(full_name="ds-modules/curriculum-guide"),
 Repository(full_name="ds-modules/EEP-147"),
 Repository(full_name="ds-modules/ESPM-163ac"),
 Repository(full_name="ds-modules/EPS-130"),
 Repository(full_name="ds-modules/MCB-163L"),
 Repository(full_name="ds-modules/CE-110"),
 Repository(full_name="ds-modules/ES-21AC-SP19"),
 Repository(full_name="ds-modules/FRENCH-43"),
 Repository(full_name="ds-modules/ECON-141"),
 Repository(full_name="ds-modules/SOC-5"),
 Repository(full_name="ds-modules/CP-101-student"),
 Repository(full_name="ds-modules/modules-textbook"),
 Repository(full_name="ds-modules/CP101BigData"),
 Repository(full_name="ds-modules/EDUC-W142"),
 Repository(full_name="ds-modules/POLSCI-3"),
 Repository(full_name="ds-modules/featured-modules"),
 Repository(full_name="ds-modules/COGSCI-1"),
 Repository(full_name="ds-modules/LS-22"),
 Repository(full_name="ds-modules/surveydata"),
 Repository(full_name="ds-modules/POLSCI-5"),
 Repository(full_name="ds-modules/SW-282"),
 Repository(full_name="ds-modules/EEP102"),
 Repository(full_name="ds-modules/CP-113B"),
 Repository(full_name="ds-modules/Bio-1B"),
 Repository(full_name="ds-modules/CP-113A"),
 Repository(full_name="ds-modules/colwrit-r4b"),
 Repository(full_name="ds-modules/Library"),
 Repository(full_name="ds-modules/PH150E-CP117AC"),
 Repository(full_name="ds-modules/SOC-5-Fall19"),
 Repository(full_name="ds-modules/Legalst-123"),
 Repository(full_name="ds-modules/EEP-147-SP20"),
 Repository(full_name="ds-modules/ECON-141-SP20"),
 Repository(full_name="ds-modules/EPS-130-SP20"),
 Repository(full_name="ds-modules/EPS-115-SP20"),
 Repository(full_name="ds-modules/course-assets"),
 Repository(full_name="ds-modules/MCB-50"),
 Repository(full_name="ds-modules/espm-c167"),
 Repository(full_name="ds-modules/EPS-118-SP20"),
 Repository(full_name="ds-modules/textbook"),
 Repository(full_name="ds-modules/ES-21AC-sp20"),
 Repository(full_name="ds-modules/ds-modules.github.io"),
 Repository(full_name="ds-modules/BUDS-su20"),
 Repository(full_name="ds-modules/workshop-su20"),
 Repository(full_name="ds-modules/POLSCI3-FA20"),
 Repository(full_name="ds-modules/MCB-140"),
 Repository(full_name="ds-modules/IB-105-ESPM-125-fa20"),
 Repository(full_name="ds-modules/ENVECON-118-FA20"),
 Repository(full_name="ds-modules/COGSCI-131-FA20"),
 Repository(full_name="ds-modules/COGSCI-C131-PSYCH-123-FA20"),
 Repository(full_name="ds-modules/EPS256-FA20"),
 Repository(full_name="ds-modules/modules-ipynb-workshop"),
 Repository(full_name="ds-modules/data-4ac"),
 Repository(full_name="ds-modules/POLSCI3-Fa20-Dev"),
 Repository(full_name="ds-modules/Infodemiology-Projects"),
 Repository(full_name="ds-modules/ps-106a"),
 Repository(full_name="ds-modules/GS102-SurveyData-FA20"),
 Repository(full_name="ds-modules/Infodemiology-Mental-Health"),
 Repository(full_name="ds-modules/Infodemiology-Nutrition"),
 Repository(full_name="ds-modules/Infodemiology-Pregnancy"),
 Repository(full_name="ds-modules/DATA198-SP21.github.io"),
 Repository(full_name="ds-modules/HCE-Materials"),
 Repository(full_name="ds-modules/DATA-198-SP21"),
 Repository(full_name="ds-modules/Econ-172-Sp21"),
 Repository(full_name="ds-modules/EPS-130-SP21"),
 Repository(full_name="ds-modules/PS-88-21-DEV"),
 Repository(full_name="ds-modules/ECON-140-SP21"),
 Repository(full_name="ds-modules/IB-161-SP21"),
 Repository(full_name="ds-modules/EEP-147-SP21"),
 Repository(full_name="ds-modules/CP-101-SP21"),
 Repository(full_name="ds-modules/Colab-data-8"),
 Repository(full_name="ds-modules/BUDS-SU21-Dev"),
 Repository(full_name="ds-modules/SOC-88-SP21"),
 Repository(full_name="ds-modules/ES-21AC-SP21"),
 Repository(full_name="ds-modules/ES-21AC-SP21-key"),
 Repository(full_name="ds-modules/Spanish"),
 Repository(full_name="ds-modules/music-30"),
 Repository(full_name="ds-modules/Deepnote-demo"),
 Repository(full_name="ds-modules/infodem-covid-babies"),
 Repository(full_name="ds-modules/infodem-mental-health"),
 Repository(full_name="ds-modules/sather-tower"),
 Repository(full_name="ds-modules/BUDS-su21"),
 Repository(full_name="ds-modules/BLDAP-Su21-student"),
 Repository(full_name="ds-modules/ENVECON-118-FA21"),
 Repository(full_name="ds-modules/ART-23AC-FA21"),
 Repository(full_name="ds-modules/ECON-140-FA21"),
 Repository(full_name="ds-modules/IB-105-ESPM-125-FA21"),
 Repository(full_name="ds-modules/global-fa21"),
 Repository(full_name="ds-modules/air-quality"),
 Repository(full_name="ds-modules/DATA88-SP22"),
 Repository(full_name="ds-modules/data8-esp"),
 Repository(full_name="ds-modules/EPS-130-SP22"),
 Repository(full_name="ds-modules/MECENG-103"),
 Repository(full_name="ds-modules/ECON-143-SP22"),
 Repository(full_name="ds-modules/ECON-140-SP22"),
 Repository(full_name="ds-modules/GLOBAL-88-SP22"),
 Repository(full_name="ds-modules/Data198-SP22"),
 Repository(full_name="ds-modules/ESPM-109E-SP22"),
 Repository(full_name="ds-modules/IB-C32"),
 Repository(full_name="ds-modules/ETHSTD-21AC-SP22"),
 Repository(full_name="ds-modules/EEP-147-SP22"),
 Repository(full_name="ds-modules/ECON-172-SP22"),
 Repository(full_name="ds-modules/sample-intro-notebooks"),
 Repository(full_name="ds-modules/datahub-homepage"),
 Repository(full_name="ds-modules/ECON-140-SU22"),
 Repository(full_name="ds-modules/BUDS-SU22"),
 Repository(full_name="ds-modules/LEGAL-190-FA22"),
 Repository(full_name="ds-modules/polisci-3"),
 Repository(full_name="ds-modules/PUBPOL-ETHSTD-C164A-SP23"),
 Repository(full_name="ds-modules/materials-x22"),
 Repository(full_name="ds-modules/EPS88-24031-FA22"),
 Repository(full_name="ds-modules/ECON-140-FA22-SB"),
 Repository(full_name="ds-modules/ECON-140-FA22-RDE"),
 Repository(full_name="ds-modules/Library-Data-Workshop-Fall-2022"),
 Repository(full_name="ds-modules/ENVECON-118-FA22"),
 Repository(full_name="ds-modules/ECON-130-FA22"),
 Repository(full_name="ds-modules/CIVENG-190"),
 Repository(full_name="ds-modules/CalTeach-FA22"),
 Repository(full_name="ds-modules/ECON-148"),
 Repository(full_name="ds-modules/CE200B"),
 Repository(full_name="ds-modules/ENVECON-118-SP23"),
 Repository(full_name="ds-modules/EPS130-21521-SP23"),
 Repository(full_name="ds-modules/ECON-140-SP23-SB"),
 Repository(full_name="ds-modules/PS88-SP23-Public"),
 Repository(full_name="ds-modules/DATA198-SP23"),
 Repository(full_name="ds-modules/Search-Engine"),
 Repository(full_name="ds-modules/E7"),
 Repository(full_name="ds-modules/EEP-147-SP23"),
 Repository(full_name="ds-modules/ECON-172-SP23")]

In [174]:
remove = 0 
for i in range(len(repo_list)):
    if repo_list[i].full_name == 'ds-modules/Library-HTRC':
        remove = i
repo_list.pop(remove)
len(repo_list)

170

## Jupyter Notebook Information

In [11]:
# NOTICE: unless you want to go over your allowed API calls per hour, only run this once. 

total_modules_ipynb = 0
ipynb_counts = []
filepaths = []
for i in range(len(repo_list)):
    rate_limit = client.get_rate_limit()
    rate = rate_limit.search
    if rate.remaining == 0:
        print('loading API...')
        time.sleep(20)
    else:
        print(f'You have {rate.remaining}/{rate.limit} API calls remaining')
    
    test_repo = client.get_repo(repo_list[i].full_name)
    print('Repo Name: ', test_repo,)
    print('Repo Link: ', f'github.com/{test_repo.full_name}')
    
    total_ipynb = 0
    test_contents = test_repo.get_contents("")
    file_contents = []

    while test_contents:
        file_content = test_contents.pop(0)
        if file_content.type == "dir":
            test_contents.extend(test_repo.get_contents(file_content.path))
        else:
            if 'ipynb' in file_content.path:
                total_ipynb += 1
            file_contents.append(file_content)
    filepaths.append(file_contents)
    
    total_modules_ipynb += total_ipynb
    ipynb_counts.append(total_ipynb)
    print('Total .ipynb files in this repo: ', total_ipynb)
    print('Total .ipynb files in ds-modules: ', total_modules_ipynb)
    print('---')

You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/core-resources")
Repo Link:  github.com/ds-modules/core-resources
Total .ipynb files in this repo:  58
Total .ipynb files in ds-modules:  58
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENGIN-7")
Repo Link:  github.com/ds-modules/ENGIN-7
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  70
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/DS-Modules")
Repo Link:  github.com/ds-modules/DS-Modules
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  70
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ISF-189")
Repo Link:  github.com/ds-modules/ISF-189
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  71
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EDUC-223B")
Repo Link:  github.com/ds-modules/EDUC-223B
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  73
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/NESTUD-190A")
Repo Link:  github.com/ds-modules/NESTUD-190A
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  85
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ETHSTD-21AC")
Repo Link:  github.com/ds-modules/ETHSTD-21AC
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  97
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/XRHETOR-R1A")
Repo Link:  github.com/ds-modules/XRHETOR-R1A
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  109
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/HIST-88")
Repo Link:  github.com/ds-modules/HIST-88
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  110
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/GWS-101")
Repo Link:  github.com/ds-modules/GWS-101
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  114
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ART-W23AC")
Repo Link:  github.com/ds-modules/ART-W23AC
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  121
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IAS-150")
Repo Link:  github.com/ds-modules/IAS-150
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  130
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SOC-130AC")
Repo Link:  github.com/ds-modules/SOC-130AC
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  139
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/INFO-290")
Repo Link:  github.com/ds-modules/INFO-290
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  142
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/GWS-131")
Repo Link:  github.com/ds-modules/GWS-131
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  143
---
You have 28/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/LINGUIS-110")
Repo Link:  github.com/ds-modules/LINGUIS-110
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  147
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/PSYCH-167AC")
Repo Link:  github.com/ds-modules/PSYCH-167AC
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  150
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/XENGLIS-31AC")
Repo Link:  github.com/ds-modules/XENGLIS-31AC
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  152
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-101B")
Repo Link:  github.com/ds-modules/ECON-101B
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  164
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/LS-88")
Repo Link:  github.com/ds-modules/LS-88
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  167
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/RDM-DeCal")
Repo Link:  github.com/ds-modules/RDM-DeCal
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  169
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-C20")
Repo Link:  github.com/ds-modules/EPS-C20
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  171
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/COGSCI-1B")
Repo Link:  github.com/ds-modules/COGSCI-1B
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  172
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MCB-288")
Repo Link:  github.com/ds-modules/MCB-288
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  173
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SPORTS")
Repo Link:  github.com/ds-modules/SPORTS
Total .ipynb files in this repo:  25
Total .ipynb files in ds-modules:  198
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IB-ESPM-105")
Repo Link:  github.com/ds-modules/IB-ESPM-105
Total .ipynb files in this repo:  15
Total .ipynb files in ds-modules:  213
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENVECON-100")
Repo Link:  github.com/ds-modules/ENVECON-100
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  214
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CUNEIF-102A")
Repo Link:  github.com/ds-modules/CUNEIF-102A
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  226
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Module-Feedback")
Repo Link:  github.com/ds-modules/Module-Feedback
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  227
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MEDST-250")
Repo Link:  github.com/ds-modules/MEDST-250
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  239
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/HIST-283")
Repo Link:  github.com/ds-modules/HIST-283
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  241
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/LEGALST-190")
Repo Link:  github.com/ds-modules/LEGALST-190
Total .ipynb files in this repo:  64
Total .ipynb files in ds-modules:  305
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/HTRC-Uncamp")
Repo Link:  github.com/ds-modules/HTRC-Uncamp
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  307
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/PACS-190")
Repo Link:  github.com/ds-modules/PACS-190
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  315
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/examples")
Repo Link:  github.com/ds-modules/examples
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  317
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/R-Module")
Repo Link:  github.com/ds-modules/R-Module
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  322
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IAS-106")
Repo Link:  github.com/ds-modules/IAS-106
Total .ipynb files in this repo:  14
Total .ipynb files in ds-modules:  336
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/nbinteract-image")
Repo Link:  github.com/ds-modules/nbinteract-image
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  337
---
You have 30/30 API calls remaining

Repo Name:  Repository(full_name="ds-modules/PH-142")
Repo Link:  github.com/ds-modules/PH-142
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  337
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/E-157AC")
Repo Link:  github.com/ds-modules/E-157AC
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  347
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MCB-32")
Repo Link:  github.com/ds-modules/MCB-32
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  359
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/HIST-160")
Repo Link:  github.com/ds-modules/HIST-160
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  364
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/curriculum-guide")
Repo Link:  github.com/ds-modules/curriculum-guide
Total .ipynb files in this repo:  17
Total .ipynb files in ds-modules:  381
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP-147")
Repo Link:  github.com/ds-modules/EEP-147
Total .ipynb files in this repo:  14
Total .ipynb files in ds-modules:  395
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ESPM-163ac")
Repo Link:  github.com/ds-modules/ESPM-163ac
Total .ipynb files in this repo:  13
Total .ipynb files in ds-modules:  408
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-130")
Repo Link:  github.com/ds-modules/EPS-130
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  413
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MCB-163L")
Repo Link:  github.com/ds-modules/MCB-163L
Total .ipynb files in this repo:  34
Total .ipynb files in ds-modules:  447
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CE-110")
Repo Link:  github.com/ds-modules/CE-110
Total .ipynb files in this repo:  21
Total .ipynb files in ds-modules:  468
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ES-21AC-SP19")
Repo Link:  github.com/ds-modules/ES-21AC-SP19
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  480
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/FRENCH-43")
Repo Link:  github.com/ds-modules/FRENCH-43
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  490
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-141")
Repo Link:  github.com/ds-modules/ECON-141
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  492
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SOC-5")
Repo Link:  github.com/ds-modules/SOC-5
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  502
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CP-101-student")
Repo Link:  github.com/ds-modules/CP-101-student
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  507
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/modules-textbook")
Repo Link:  github.com/ds-modules/modules-textbook
Total .ipynb files in this repo:  82
Total .ipynb files in ds-modules:  589
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CP101BigData")
Repo Link:  github.com/ds-modules/CP101BigData
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  593
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EDUC-W142")
Repo Link:  github.com/ds-modules/EDUC-W142
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  597
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/POLSCI-3")
Repo Link:  github.com/ds-modules/POLSCI-3
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  605
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/featured-modules")
Repo Link:  github.com/ds-modules/featured-modules
Total .ipynb files in this repo:  53
Total .ipynb files in ds-modules:  658
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/COGSCI-1")
Repo Link:  github.com/ds-modules/COGSCI-1
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  661
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/LS-22")
Repo Link:  github.com/ds-modules/LS-22
Total .ipynb files in this repo:  20
Total .ipynb files in ds-modules:  681
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/surveydata")
Repo Link:  github.com/ds-modules/surveydata
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  687
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/POLSCI-5")
Repo Link:  github.com/ds-modules/POLSCI-5
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  691
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SW-282")
Repo Link:  github.com/ds-modules/SW-282
Total .ipynb files in this repo:  20
Total .ipynb files in ds-modules:  711
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP102")
Repo Link:  github.com/ds-modules/EEP102
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  718
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CP-113B")
Repo Link:  github.com/ds-modules/CP-113B
Total .ipynb files in this repo:  25
Total .ipynb files in ds-modules:  743
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Bio-1B")
Repo Link:  github.com/ds-modules/Bio-1B
Total .ipynb files in this repo:  21
Total .ipynb files in ds-modules:  764
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CP-113A")
Repo Link:  github.com/ds-modules/CP-113A
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  768
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/colwrit-r4b")
Repo Link:  github.com/ds-modules/colwrit-r4b
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  770
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Library")
Repo Link:  github.com/ds-modules/Library
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  777
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/PH150E-CP117AC")
Repo Link:  github.com/ds-modules/PH150E-CP117AC
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  777
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SOC-5-Fall19")
Repo Link:  github.com/ds-modules/SOC-5-Fall19
Total .ipynb files in this repo:  11
Total .ipynb files in ds-modules:  788
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Legalst-123")
Repo Link:  github.com/ds-modules/Legalst-123
Total .ipynb files in this repo:  96
Total .ipynb files in ds-modules:  884
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP-147-SP20")
Repo Link:  github.com/ds-modules/EEP-147-SP20
Total .ipynb files in this repo:  30
Total .ipynb files in ds-modules:  914
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-141-SP20")
Repo Link:  github.com/ds-modules/ECON-141-SP20
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  916
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-130-SP20")
Repo Link:  github.com/ds-modules/EPS-130-SP20
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  924
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-115-SP20")
Repo Link:  github.com/ds-modules/EPS-115-SP20
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  934
---
You have 30/30 API calls remaining

Repo Name:  Repository(full_name="ds-modules/course-assets")
Repo Link:  github.com/ds-modules/course-assets
Total .ipynb files in this repo:  93
Total .ipynb files in ds-modules:  1027
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MCB-50")
Repo Link:  github.com/ds-modules/MCB-50
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  1029
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/espm-c167")
Repo Link:  github.com/ds-modules/espm-c167
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  1033
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-118-SP20")
Repo Link:  github.com/ds-modules/EPS-118-SP20
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  1035
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/textbook")
Repo Link:  github.com/ds-modules/textbook
Total .ipynb files in this repo:  155
Total .ipynb files in ds-modules:  1190
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ES-21AC-sp20")
Repo Link:  github.com/ds-modules/ES-21AC-sp20
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  1197
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ds-modules.github.io")
Repo Link:  github.com/ds-modules/ds-modules.github.io
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1197
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/BUDS-su20")
Repo Link:  github.com/ds-modules/BUDS-su20
Total .ipynb files in this repo:  100
Total .ipynb files in ds-modules:  1297
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/workshop-su20")
Repo Link:  github.com/ds-modules/workshop-su20
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  1309
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/POLSCI3-FA20")
Repo Link:  github.com/ds-modules/POLSCI3-FA20
Total .ipynb files in this repo:  20
Total .ipynb files in ds-modules:  1329
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MCB-140")
Repo Link:  github.com/ds-modules/MCB-140
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1329
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IB-105-ESPM-125-fa20")
Repo Link:  github.com/ds-modules/IB-105-ESPM-125-fa20
Total .ipynb files in this repo:  14
Total .ipynb files in ds-modules:  1343
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENVECON-118-FA20")
Repo Link:  github.com/ds-modules/ENVECON-118-FA20
Total .ipynb files in this repo:  29
Total .ipynb files in ds-modules:  1372
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/COGSCI-131-FA20")
Repo Link:  github.com/ds-modules/COGSCI-131-FA20
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1372
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/COGSCI-C131-PSYCH-123-FA20")
Repo Link:  github.com/ds-modules/COGSCI-C131-PSYCH-123-FA20
Total .ipynb files in this repo:  21
Total .ipynb files in ds-modules:  1393
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS256-FA20")
Repo Link:  github.com/ds-modules/EPS256-FA20
Total .ipynb files in this repo:  34
Total .ipynb files in ds-modules:  1427
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/modules-ipynb-workshop")
Repo Link:  github.com/ds-modules/modules-ipynb-workshop
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  1434
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/data-4ac")
Repo Link:  github.com/ds-modules/data-4ac
Total .ipynb files in this repo:  14
Total .ipynb files in ds-modules:  1448
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/POLSCI3-Fa20-Dev")
Repo Link:  github.com/ds-modules/POLSCI3-Fa20-Dev
Total .ipynb files in this repo:  38
Total .ipynb files in ds-modules:  1486
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Infodemiology-Projects")
Repo Link:  github.com/ds-modules/Infodemiology-Projects
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  1496
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ps-106a")
Repo Link:  github.com/ds-modules/ps-106a
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  1497
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/GS102-SurveyData-FA20")
Repo Link:  github.com/ds-modules/GS102-SurveyData-FA20
Total .ipynb files in this repo:  15
Total .ipynb files in ds-modules:  1512
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Infodemiology-Mental-Health")
Repo Link:  github.com/ds-modules/Infodemiology-Mental-Health
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  1514
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Infodemiology-Nutrition")
Repo Link:  github.com/ds-modules/Infodemiology-Nutrition
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  1516
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Infodemiology-Pregnancy")
Repo Link:  github.com/ds-modules/Infodemiology-Pregnancy
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  1520
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/DATA198-SP21.github.io")
Repo Link:  github.com/ds-modules/DATA198-SP21.github.io
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  1524
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/HCE-Materials")
Repo Link:  github.com/ds-modules/HCE-Materials
Total .ipynb files in this repo:  12
Total .ipynb files in ds-modules:  1536
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/DATA-198-SP21")
Repo Link:  github.com/ds-modules/DATA-198-SP21
Total .ipynb files in this repo:  21
Total .ipynb files in ds-modules:  1557
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Econ-172-Sp21")
Repo Link:  github.com/ds-modules/Econ-172-Sp21
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1557
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-130-SP21")
Repo Link:  github.com/ds-modules/EPS-130-SP21
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  1562
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/PS-88-21-DEV")
Repo Link:  github.com/ds-modules/PS-88-21-DEV
Total .ipynb files in this repo:  66
Total .ipynb files in ds-modules:  1628
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-SP21")
Repo Link:  github.com/ds-modules/ECON-140-SP21
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  1634
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IB-161-SP21")
Repo Link:  github.com/ds-modules/IB-161-SP21
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1634
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP-147-SP21")
Repo Link:  github.com/ds-modules/EEP-147-SP21
Total .ipynb files in this repo:  19
Total .ipynb files in ds-modules:  1653
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CP-101-SP21")
Repo Link:  github.com/ds-modules/CP-101-SP21
Total .ipynb files in this repo:  20
Total .ipynb files in ds-modules:  1673
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Colab-data-8")
Repo Link:  github.com/ds-modules/Colab-data-8
Total .ipynb files in this repo:  87
Total .ipynb files in ds-modules:  1760
---
You have 30/30 API calls remaining

Repo Name:  Repository(full_name="ds-modules/BUDS-SU21-Dev")
Repo Link:  github.com/ds-modules/BUDS-SU21-Dev
Total .ipynb files in this repo:  104
Total .ipynb files in ds-modules:  1864
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/SOC-88-SP21")
Repo Link:  github.com/ds-modules/SOC-88-SP21
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  1873
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ES-21AC-SP21")
Repo Link:  github.com/ds-modules/ES-21AC-SP21
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  1882
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ES-21AC-SP21-key")
Repo Link:  github.com/ds-modules/ES-21AC-SP21-key
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  1891
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Spanish")
Repo Link:  github.com/ds-modules/Spanish
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  1892
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/music-30")
Repo Link:  github.com/ds-modules/music-30
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  1900
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Deepnote-demo")
Repo Link:  github.com/ds-modules/Deepnote-demo
Total .ipynb files in this repo:  63
Total .ipynb files in ds-modules:  1963
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/infodem-covid-babies")
Repo Link:  github.com/ds-modules/infodem-covid-babies
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  1964
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/infodem-mental-health")
Repo Link:  github.com/ds-modules/infodem-mental-health
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  1964
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/sather-tower")
Repo Link:  github.com/ds-modules/sather-tower
Total .ipynb files in this repo:  5
Total .ipynb files in ds-modules:  1969
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/BUDS-su21")
Repo Link:  github.com/ds-modules/BUDS-su21
Total .ipynb files in this repo:  27
Total .ipynb files in ds-modules:  1996
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/BLDAP-Su21-student")
Repo Link:  github.com/ds-modules/BLDAP-Su21-student
Total .ipynb files in this repo:  26
Total .ipynb files in ds-modules:  2022
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENVECON-118-FA21")
Repo Link:  github.com/ds-modules/ENVECON-118-FA21
Total .ipynb files in this repo:  28
Total .ipynb files in ds-modules:  2050
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ART-23AC-FA21")
Repo Link:  github.com/ds-modules/ART-23AC-FA21
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2053
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-FA21")
Repo Link:  github.com/ds-modules/ECON-140-FA21
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  2060
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IB-105-ESPM-125-FA21")
Repo Link:  github.com/ds-modules/IB-105-ESPM-125-FA21
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  2066
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/global-fa21")
Repo Link:  github.com/ds-modules/global-fa21
Total .ipynb files in this repo:  52
Total .ipynb files in ds-modules:  2118
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/air-quality")
Repo Link:  github.com/ds-modules/air-quality
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  2128
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/DATA88-SP22")
Repo Link:  github.com/ds-modules/DATA88-SP22
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  2138
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/data8-esp")
Repo Link:  github.com/ds-modules/data8-esp
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2138
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS-130-SP22")
Repo Link:  github.com/ds-modules/EPS-130-SP22
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  2145
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/MECENG-103")
Repo Link:  github.com/ds-modules/MECENG-103
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2145
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-143-SP22")
Repo Link:  github.com/ds-modules/ECON-143-SP22
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  2149
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-SP22")
Repo Link:  github.com/ds-modules/ECON-140-SP22
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  2155
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/GLOBAL-88-SP22")
Repo Link:  github.com/ds-modules/GLOBAL-88-SP22
Total .ipynb files in this repo:  49
Total .ipynb files in ds-modules:  2204
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Data198-SP22")
Repo Link:  github.com/ds-modules/Data198-SP22
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  2206
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ESPM-109E-SP22")
Repo Link:  github.com/ds-modules/ESPM-109E-SP22
Total .ipynb files in this repo:  20
Total .ipynb files in ds-modules:  2226
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/IB-C32")
Repo Link:  github.com/ds-modules/IB-C32
Total .ipynb files in this repo:  9
Total .ipynb files in ds-modules:  2235
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ETHSTD-21AC-SP22")
Repo Link:  github.com/ds-modules/ETHSTD-21AC-SP22
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2238
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP-147-SP22")
Repo Link:  github.com/ds-modules/EEP-147-SP22
Total .ipynb files in this repo:  4
Total .ipynb files in ds-modules:  2242
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-172-SP22")
Repo Link:  github.com/ds-modules/ECON-172-SP22
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2242
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/sample-intro-notebooks")
Repo Link:  github.com/ds-modules/sample-intro-notebooks
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2245
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/datahub-homepage")
Repo Link:  github.com/ds-modules/datahub-homepage
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2245
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-SU22")
Repo Link:  github.com/ds-modules/ECON-140-SU22
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2245
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/BUDS-SU22")
Repo Link:  github.com/ds-modules/BUDS-SU22
Total .ipynb files in this repo:  40
Total .ipynb files in ds-modules:  2285
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/LEGAL-190-FA22")
Repo Link:  github.com/ds-modules/LEGAL-190-FA22
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  2293
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/polisci-3")
Repo Link:  github.com/ds-modules/polisci-3
Total .ipynb files in this repo:  18
Total .ipynb files in ds-modules:  2311
---
You have 30/30 API calls remaining

Repo Name:  Repository(full_name="ds-modules/PUBPOL-ETHSTD-C164A-SP23")
Repo Link:  github.com/ds-modules/PUBPOL-ETHSTD-C164A-SP23
Total .ipynb files in this repo:  19
Total .ipynb files in ds-modules:  2330
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/materials-x22")
Repo Link:  github.com/ds-modules/materials-x22
Total .ipynb files in this repo:  21
Total .ipynb files in ds-modules:  2351
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS88-24031-FA22")
Repo Link:  github.com/ds-modules/EPS88-24031-FA22
Total .ipynb files in this repo:  34
Total .ipynb files in ds-modules:  2385
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-FA22-SB")
Repo Link:  github.com/ds-modules/ECON-140-FA22-SB
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  2391
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-FA22-RDE")
Repo Link:  github.com/ds-modules/ECON-140-FA22-RDE
Total .ipynb files in this repo:  55
Total .ipynb files in ds-modules:  2446
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Library-Data-Workshop-Fall-2022")
Repo Link:  github.com/ds-modules/Library-Data-Workshop-Fall-2022
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  2447
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENVECON-118-FA22")
Repo Link:  github.com/ds-modules/ENVECON-118-FA22
Total .ipynb files in this repo:  34
Total .ipynb files in ds-modules:  2481
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-130-FA22")
Repo Link:  github.com/ds-modules/ECON-130-FA22
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  2487
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CIVENG-190")
Repo Link:  github.com/ds-modules/CIVENG-190
Total .ipynb files in this repo:  6
Total .ipynb files in ds-modules:  2493
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CalTeach-FA22")
Repo Link:  github.com/ds-modules/CalTeach-FA22
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2496
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-148")
Repo Link:  github.com/ds-modules/ECON-148
Total .ipynb files in this repo:  10
Total .ipynb files in ds-modules:  2506
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/CE200B")
Repo Link:  github.com/ds-modules/CE200B
Total .ipynb files in this repo:  8
Total .ipynb files in ds-modules:  2514
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ENVECON-118-SP23")
Repo Link:  github.com/ds-modules/ENVECON-118-SP23
Total .ipynb files in this repo:  7
Total .ipynb files in ds-modules:  2521
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EPS130-21521-SP23")
Repo Link:  github.com/ds-modules/EPS130-21521-SP23
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2524
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-140-SP23-SB")
Repo Link:  github.com/ds-modules/ECON-140-SP23-SB
Total .ipynb files in this repo:  3
Total .ipynb files in ds-modules:  2527
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/PS88-SP23-Public")
Repo Link:  github.com/ds-modules/PS88-SP23-Public
Total .ipynb files in this repo:  16
Total .ipynb files in ds-modules:  2543
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/DATA198-SP23")
Repo Link:  github.com/ds-modules/DATA198-SP23
Total .ipynb files in this repo:  2
Total .ipynb files in ds-modules:  2545
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/Search-Engine")
Repo Link:  github.com/ds-modules/Search-Engine
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  2546
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/E7")
Repo Link:  github.com/ds-modules/E7
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2546
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/EEP-147-SP23")
Repo Link:  github.com/ds-modules/EEP-147-SP23
Total .ipynb files in this repo:  1
Total .ipynb files in ds-modules:  2547
---
You have 30/30 API calls remaining
Repo Name:  Repository(full_name="ds-modules/ECON-172-SP23")
Repo Link:  github.com/ds-modules/ECON-172-SP23
Total .ipynb files in this repo:  0
Total .ipynb files in ds-modules:  2547
---

In [175]:
max_ipynb_index = np.argmax(ipynb_counts)
repo_list[max_ipynb_index]

Repository(full_name="ds-modules/textbook")

In [176]:
np.mean(ipynb_counts), np.median(ipynb_counts)

(14.98235294117647, 7.0)

In [177]:
# sorts indices of ipynb_counts, allowing us to see repos with the lowest and highest number of jupyter notebooks 
ipynb_counts_max = np.flip(np.argsort(ipynb_counts))
ipynb_counts_min = np.argsort(ipynb_counts)

max10_repos = ipynb_counts_max[0:10]
min5_repos = ipynb_counts_min[0:10]

In [178]:
# 15 repos have 0 Jupyter Notebooks 
ipynb_counts.count(0)
four_or_less = sum([ipynb_counts.count(i) for i in range(5)])
four_or_less

67

In [179]:
# First line gets all repos with a particular name in it's title
# Second line gets all the indices of repo_list that correspond to those repos 

ECON = ['ECON' in i.full_name for i in repo_list]
econ_indices = [i for i, x in enumerate(ECON) if x]
econ_ipynb = 0 
for i in econ_indices:
    econ_ipynb += ipynb_counts[i]

MCB = ['MCB' in i.full_name for i in repo_list]
mcb_indices = [i for i, x in enumerate(MCB) if x]
mcb_ipynb = 0 
for i in mcb_indices:
    mcb_ipynb += ipynb_counts[i]

COGSCI = ['COGSCI' in i.full_name for i in repo_list]
cogsci_indices = [i for i, x in enumerate(COGSCI) if x]
cogsci_ipynb = 0 
for i in cogsci_indices:
    cogsci_ipynb += ipynb_counts[i]

PSYCH = ['PSYCH' in i.full_name for i in repo_list]
psych_indices = [i for i, x in enumerate(PSYCH) if x]
psych_ipynb = 0 
for i in psych_indices:
    psych_ipynb += ipynb_counts[i]

ESPM = ['ESPM' in i.full_name for i in repo_list]
espm_indices = [i for i, x in enumerate(ESPM) if x]
espm_ipynb = 0 
for i in espm_indices:
    espm_ipynb += ipynb_counts[i]

In [180]:
econ_ipynb, mcb_ipynb, cogsci_ipynb, psych_ipynb, espm_ipynb

(218, 49, 25, 24, 68)

## Repo Information

In [181]:
repo_list[0].created_at

datetime.datetime(2017, 3, 1, 2, 26, 6)

In [182]:
year_repos = {2017:0, 2018:0, 2019:0, 2020:0, 2021:0, 2022:0, 2023:0}
year_notebooks = {2017:0, 2018:0, 2019:0, 2020:0, 2021:0, 2022:0, 2023:0}
months = [i for i in range(1, 13)]
spring = [1,2,3,4,5]
fall = [8, 9, 10, 11, 12]

for i in range(len(repo_list)):
    year = repo_list[i].created_at.year
    year_repos[year] += 1
    year_notebooks[year] += ipynb_counts[i]
# year_totals[2018] += year_totals[2017]
# year_totals[2019] += year_totals[2018]
# year_totals[2020] += year_totals[2019]
# year_totals[2021] += year_totals[2020]
# year_totals[2022] += year_totals[2021]
# year_totals[2023] += year_totals[2022]

In [183]:
year_repos

{2017: 32, 2018: 13, 2019: 27, 2020: 32, 2021: 28, 2022: 30, 2023: 8}

In [184]:
year_notebooks

{2017: 305, 2018: 103, 2019: 476, 2020: 673, 2021: 581, 2022: 383, 2023: 26}

## File Information

In [53]:
# Get file content: decoded content is a byte string -> we decode to a regular string 
repo_list[1].get_contents(filepaths[1][6].path).decoded_content.decode('utf-8')

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "collapsed": true\n   },\n   "source": [\n    "# E7: Introduction to Computer Programming for Scientists and Engineers"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Lab Assignment 2"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "For each question, you will have to fill in one or more Python functions. We provide an autograder with a number of test cases that you can use to test your function. Note that the fact that your function works for all test cases thus provided does necessarily guarantee\\n",\n    "that it will work for all possible test cases relevant to the question. It is your responsibility\\n",\n    "to test your function thoroughly, to ensure that it will also work in situations not covered\\n",\n    "by the test cases provided"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 1,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "# Please run this cell, and do not modify the contets\\n",\n    "import math\\n",\n    "import numpy as np\\n",\n    "import matplotlib.pyplot as plt\\n",\n    "np.seterr(all=\'ignore\');\\n",\n    "# %run lab2_ag.py"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 1\\n",\n    "\\n",\n    "Write a Python function that calculates the roots of a quadratic equation $ax^2+bx+\\n",\n    "c = 0$ of unknown $x$, using the quadratic formula below. \\n",\n    "\\n",\n    "$$x = \\\\frac{-b\\\\pm \\\\sqrt{b^2-4ac}}{2a}$$"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "The function output should be a two element tuple. The first element should be the root computed by setting the $\\\\pm$ to $+$, and the second element should be the root computed by setting the $\\\\pm$ to $-$. You may assume $b2 - 4ac \\\\ge 0$."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 2,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def solve_quadratic(a, b, c):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> solve_quadratic(1, -7, 10)\\n",\n    "    (5.0, 2.0)\\n",\n    "    >>> solve_quadratic(5, -23, 2)\\n",\n    "    (4.511334438749598, 0.08866556125040184)\\n",\n    "    \\"\\"\\"\\n",\n    "    disc = math.sqrt(b*b-4.*a*c)\\n",\n    "    return (-b+disc)/(2.*a), (-b-disc)/(2.*a)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 2\\n",\n    "\\n",\n    "Write a Python function that computes the Euclidean distances between two sets of\\n",\n    "points. The x-coordinates for the first set of points will be stored in a column vector\\n",\n    "`X_1`, the y-coordinates for the first set of points in `Y_1`, the x-coordinates for the second\\n",\n    "set of points will be stored in a column vector `X_2`, the y-coordinates for the second\\n",\n    "set of points in `Y_2`. `X_1`, `Y_1`, `X_2`, and `Y_2` are $N$ by $1$ arrays where $N$ is the number\\n",\n    "of points in each set. Note that, for a single pair of points, $(x_1, y_1)$ and $(x_2, y_2)$, the\\n",\n    "Euclidean distance can be obtained from the distance formula:\\n",\n    "\\n",\n    "$$ \\\\text{Euclidean distance} = \\\\sqrt{(x_1-x_2)^2 + (y_1-y_2)^2} $$"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 3,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def euclidean_distance(x1, y1, x2, y2):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> euclidean_distance(np.array([0,0]),np.array([0,0]),np.array([3,5]),np.array([4,12]))\\n",\n    "    array([  5.,  13.])\\n",\n    "    \\"\\"\\"\\n",\n    "    x = x1 - x2\\n",\n    "    y = y1 - y2\\n",\n    "    return np.sqrt(x*x+y*y)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 3\\n",\n    "\\n",\n    "Carbon dating is a method for determining the age of an object containing the ra-\\n",\n    "dioisotope carbon-14. Since carbon-14 is subject to radioactive decay, the number of\\n",\n    "carbon-14 atoms in a sample will decay over time according to the following exponential\\n",\n    "decay law:\\n",\n    "\\n",\n    "$$ N(t) = N_0 e^{-\\\\lambda t} $$\\n",\n    "\\n",\n    "where $N_0$ is the number of atoms of the isotope in the original sample, $N(t)$ is the remaining number of atoms after a time $t$, $\\\\lambda$ is the expoential decay constant and $t$ is the time.\\n",\n    "\\n",\n    "Write a function that calculates the remaining fraction of carbon-14 in a sample after\\n",\n    "a certain amount of time (in years). The remaining fraction is defined as the ratio of\\n",\n    "the number of atoms at the present time ($N(t)$) to the initial number of atoms ($N_0$).\\n",\n    "You can re-arrange the decay formula above to find an expression for this ratio.\\n",\n    "\\n",\n    "Assume $\\\\lambda = 0.00012097 \\\\: \\\\text{years}^{-1}$."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 4,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def c14_dating(time):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> c14_dating(10000)\\n",\n    "    0.29828675203393595\\n",\n    "    >>> c14_dating(5730)\\n",\n    "    0.49999454030978113\\n",\n    "    \\"\\"\\"\\n",\n    "    return math.e**(-time*0.00012097)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 4\\n",\n    "\\n",\n    "A ball is launched in the air with initial velocity $v_o$ from an initial position of coordinates $(x_0, y_0)$ as illustrated below: \\n",\n    "\\n",\n    "<img src=\\"resources/E7_Lab2_1.jpg\\" style=\\"width: 300px;\\"/>\\n",\n    "<center>*Figure 1: Ball launching at angle $\\\\theta$ from the x-axis with inital velocity $v_0$*</center>\\n",\n    "\\n",\n    "The ball is launched at an angle $\\\\theta$ (expressed in degrees) from the x-axis. The\\n",\n    "equations describing the motion (i.e. the position of the ball $(x(t), y(t)$) as a function\\n",\n    "of time $t$) of the ball are:\\n",\n    "\\n",\n    "$$ x(t) = x_0 + v_0 t \\\\cos(\\\\theta) $$\\n",\n    "$$ y(t) = y_0 + v_0 t \\\\sin(\\\\theta) - \\\\frac{1}{2}gt^2 $$\\n",\n    "\\n",\n    "where $g$ is the gravitational acceleration ($g = 9.81 m s^22$). Since $\\\\theta$ is given in degrees,\\n",\n    "you will want to convert it first into radians before using the `sin` or `cos` functions."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "a. Write a function that calculates the time at which the ball reaches the ground.\\n",\n    "\\n",\n    "Note that when the ball hits the ground, $y = 0$. Also, before writing your code,\\n",\n    "don\'t forget to use pen and paper to manipulate the equation(s) above and get a\\n",\n    "mathematical expression for time."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 5,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "# run this cell to create a global variable g, but make sure you don\'t have any other global variables also named g\\n",\n    "g = 9.81"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 6,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def proj_time(y0, v0, theta):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> proj_time(0, 15, 40)\\n",\n    "    1.9657113446071535\\n",\n    "    \\"\\"\\"\\n",\n    "    b = v0 * math.sin(np.deg2rad(theta))\\n",\n    "    time = -(-b - math.sqrt(b**2+2.*g*y0))/g\\n",\n    "    return time"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "b. Write a function that calculates the horizontal distance traveled by the ball before\\n",\n    "it reaches the ground. You can use the function `proj_time` and the equations of\\n",\n    "motion."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 7,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def proj_distance(y0, v0, theta):\\n",\n    "        \\"\\"\\"\\n",\n    "        >>> proj_distance(0, 15, 40)\\n",\n    "        22.587333784683665\\n",\n    "        \\"\\"\\"\\n",\n    "        time = proj_time(y0, v0, theta)\\n",\n    "        dist = v0 * time * math.cos(np.deg2rad(theta))\\n",\n    "        return dist"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 5\\n",\n    "\\n",\n    "Cell towers and triangulation. Note that part 5b will rely on the function you develop\\n",\n    "in part 5a."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "a. Write a function that draws a circle centered at the point of coordinates $(x_c, y_c)$\\n",\n    "and with radius $r_c$."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "Your function should return nothing, but it should plot a circle with a dashed black\\n",\n    "line for the perimeter and a red point for the center. Multiple function calls, along\\n",\n    "with the command hold on should plot multiple circles. For example, the code:\\n",\n    "\\n",\n    "```PYTHON\\n",\n    "fig, ax = plt.subplots()\\n",\n    "ax.set_xlim((-5,5))\\n",\n    "ax.set_ylim((-5,5))\\n",\n    "draw_circle(ax, 0, 0, 4)\\n",\n    "draw_circle(ax, 2, 2, 3)\\n",\n    "plt.show()\\n",\n    "```\\n",\n    "\\n",\n    "should plot something similar to Figure 2 here:\\n",\n    "\\n",\n    "<img src=\\"resources/E7_Lab5_1.jpg\\" style=\\"width: 500px;\\"/>\\n",\n    "<center>*Figure 2*</center>\\n",\n    "\\n",\n    "Don\'t worry about making the plot look exactly like Figure 2."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 46,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def draw_circle(ax, xc, yc, rc):\\n",\n    "    circle = plt.Circle((xc, yc), rc, fill=False, linestyle=\'--\')\\n",\n    "    ax.plot((xc), (yc), \'o\', color = \'red\')\\n",\n    "    ax.add_artist(circle)\\n",\n    "    # plt.show()"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 47,\n   "metadata": {},\n   "outputs": [\n    {\n     "data": {\n      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXYAAAD8CAYAAABjAo9vAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\\nAAALEgAACxIB0t1+/AAAIABJREFUeJzt3XdcVnX/x/HXly0oggu3oKI5coErb7fkTM2VepsrJTW1\\n1DQ1s241R/4qs7QcmVqWkrn3Ss0FApoTByC4VzgBGdf394fmXd2WIBeca3yej4cP4/Kcc727sjeH\\n7/me71Faa4QQQtgOB6MDCCGEMC8pdiGEsDFS7EIIYWOk2IUQwsZIsQshhI2RYhdCCBsjxS6EEDZG\\nil0IIWyMFLsQQtgYJyPetECBAtrX19eItxbC5mmtUUpx584dkpKSSEtLA6BYsWLcvHmT69evk5aW\\nRnp6Ov7+/gCcOXMGAKUUPj4++Pj4EBUVRWpqKlprcuXKhb+/P+fPn+fatWs4ODjg6OhIxYoVSU5O\\n5sqVKzg5OeHo6Ej+/Plxd3fnzp07uLi44OrqilLKsM/DlkRERNzQWhd82naGFLuvry/h4eFGvLUQ\\nVs9kMhEdHc2pU6eoUKECxYoVo3v37sTExBAbG0uHDh345ptv+OCDD7h9+zb58+fHx8eH/v37Exsb\\ny+XLl/H29sbLy4uCBQvi5JS5GjCZTNy7d4+EhASKFy/O9evX2b9/P7du3SIhIYFmzZrh7+9P27Zt\\niY2N5cyZM/Tp04evvvqKadOmkZiYiJ+fH6VLl6ZBgwbZ9CnZJqVUXIa2M2KtmMDAQC3FLsTTpaen\\nc/r0aSIiInjppZc4evQorVu3xsvLiwoVKjBy5EiaNGnCypUr8fX1xc/PD29vb6Nj/0l6ejr379/H\\n09OTlStXcvjwYWJiYkhOTubHH3/ks88+Y/fu3dSoUYMaNWrQuHFj3NzcjI5tkZRSEVrrwKduJ8Uu\\nhOWIj48nLCyMTp06MW/ePIYPH46Pjw81atTg//7v/yhYsCCJiYnkz5/f6KhmEx8fz759+4iMjCQi\\nIoLly5cTERHB559/TkBAALVq1aJBgwa4u7sbHdVwUuxCWIHU1FScnZ2ZNWsWM2fO5LfffqNJkyZ8\\n//33JCQk4OTkhJeXl9Exc9z169fZuXMnERER7Nu3jwkTJlCpUiXmz59PUFAQ1atXx9HR0eiYOU6K\\nXQgLFRoayoYNG9i2bRt37tzh6NGjHDhwAFdXV6pWrYqDg0xWe5KLFy/y0UcfsW3bNq5cucLcuXPp\\n2LEj8fHxlCxZ0uh4OUKKXQgLkZqaytatW7lw4QLBwcGMHDkSBwcHgoKCqFevHrly5TI6otW5ePEi\\nzs7OODo6UqlSJfLmzcsrr7xCr169KFOmjNHxsk1Gi92QWTFC2IsxY8Ywf/58ypUrx2uvvQbA9OnT\\nDU5l/YoVK/b4ny9fvszBgwdZunQpBw4cwM/Pj88//5z27dtTqlQpA1MaR4pdCDPRWnPw4EF++OEH\\nbt26xTfffEOjRo0YMGCA3RZMTlBKUatWLWrVqgXAnTt3OHHiBBMnTqRcuXK89957tGzZ0uCUOUsG\\n84TIot+HM1u0aEGPHj3w9PTknXfeAaB58+ZS6jnM09OTOXPmcOnSJcaNG0e+fPlITEykW7dubN++\\nHXt4HKicsQvxjKKjo/n88885evQo27dvZ/HixRQqVEjusrQQLi4utGrVCoDk5GQaN27Mm2++iVKK\\nzz//nEaNGhkbMBvJGbsQz2D06NHUqVMHNzc3vvnmGwB8fHyk1C2Um5sbwcHBHD16lBkzZuDj48PV\\nq1cZM2YM58+fNzqe2UmxC5EBKSkpzJ8/n+bNm5Oamkq/fv2Ii4tj6tSpdjPVzhYopWjatCkVKlQA\\nICkpiapVq9KlSxdOnz5tcDrzkWIX4im2bdtGhQoVCAkJYdSoUTg5OVG2bFm5E9LK+fj4MGPGDM6d\\nO8e//vUv3NzcOH/+PCdPnjQ6WpZJsQvxBFprNm7cyN27d8mXLx/z589ny5YtNG3aVIZbbIynpydD\\nhw6lZMmSHDlyhAYNGvDaa69Z9RCNFLsQf7F//34aNWrEiBEjiI+Pf7wwlbB9rVu35syZM/j4+NCg\\nQQMePHhgdKRnIsUuxB/ExcXRvXt3evfuzZEjR6hUqZLRkUQO8/LyYvLkyURFReHq6kqvXr2YNGkS\\niYmJRkfLMCl2YfeSkpIYN24c7777LqVKleLs2bP06dMn0+uUC9vi6uoKwHvvvceRI0eoXLky27Zt\\nMzhVxpit2JVSjkqpQ0qpdeY6phDZbfv27VSpUoXTp08zePBgALtcNVD8vbJlyxISEsLs2bO5ceMG\\nWmt+++03o2P9I3Oesb8JWP/lZGEXUlNTAYiIiGDGjBmEhIRQpEgRg1MJS9aiRQu6du3KsWPHqFCh\\nAkuWLLHYu1jNUuxKqeJAa2C+OY4nRHbaunUr5cuX59y5c4waNYrWrVsbHUlYkeeff57169czefJk\\nOnTowN27d42O9D/MNYg4AxgF5DHT8YQwC5PJxN27d0lMTCRfvny89tprbNmyhf79+7N//368vb1J\\nTk5mw4YNpKeno7WmVq1aVK1alWXLlpGWloajoyOFChWiSZMmxMTEkJSUhLe3N97e3ri5ucn0RzsU\\nGBhIZGQkCxYswMPDg1u3blnUA1GyXOxKqTbANa11hFKq0T9sFwwEA3KnnnhmWmuuX79ObGwssbGx\\n1KtXDw8PD9555x0SEhK4desWzZs3Z+TIkdSrV4/Q0FDc3d2pVKkSmzdv5sqVKwQGBnL69Gmio6Op\\nX78+iYmJ7Nq1C0dHR5RSFC9enKpVq7Jjxw7u3r2LyWTC39+fJk2asGjRIn788cfH73XlyhV27drF\\nqFGj8PLywtvbmzFjxlC7dm3+85//UKhQIfz8/KhcubJNrxNuj1xdXRk4cCBaa5o0aULbtm0ZP368\\nRTwoJcsP2lBKTQFeBdIAN8ATWKG17vF3+8iDNsQ/SUlJwcXFhf379xMaGkpMTAznzp1j+fLlfP/9\\n94wYMQI/Pz/8/PwYO3Ys5cuX57vvvntcrKVLl6ZMmTLcuXMHd3d39u/fz9SpU1mzZk22XBi9d+8e\\n58+ff1z2VapUIX/+/HzyySdcuXKF2NhYatWqxfjx42nRogW//fYbfn5+PP/884wbN474+HhSU1Mp\\nWbIkzs7OZs8nst+VK1fo3LkzXl5efPvtt9l29m7IE5QenbG/rbVu80/bSbELeFjg9+/fx9vbm5Ej\\nR7J3717OnDlDuXLl2Lt3L7Nnz+bkyZOULl0aPz8/WrVqhbOzc4aHPrTWfPHFF0yaNIlFixbRokWL\\nbP43erqrV68SExNDbGwsd+/e5fXXX2fmzJl8+umnXLp0icKFC7N7924cHBwICwujRo0a+Pr6ynCP\\nFUhJSWHs2LH07duXihUrZst7ZLTY0Vqb7RfQCFj3tO0CAgK0sC/Jycn6/v37+tatWzo4OFgHBgbq\\nXLly6ffee09rrfX333+vd+7cqS9fvqxNJpNZ3jMyMlJXq1ZNR0dHm+V42S0lJUVHR0frtLQ0HR4e\\nrl966SVdtGhR7e3trTdu3KgfPHigly5dqk+fPq3T09ONjiv+wZtvvqlDQkLMflwgXGekizOykbl/\\nSbHbNpPJpE0mkz558qR+7bXXdPXq1XWuXLn0smXLdGpqqp45c6beu3evvnfvXra8/9WrV/XixYu1\\n1lqnpaVly3vkpMuXL+vbt2/rq1ev6vbt2+uSJUvqvHnz6k8++URrrfXGjRv1pUuXDE4p/igiIkKX\\nKlVKjx8/3mwnKlpnvNjl1jphFteuXWPTpk1s3bqVbdu2sWnTJry8vKhRowb9+/enSpUqjx/aPGTI\\nkGzLcfnyZZo1a0anTp0A27jZqHDhwsDDxapWrlwJwPXr1x/PxV+0aBGbN2+mWLFivPbaa7z11luY\\nTCaLuIhnr2rUqMHBgwcJCgoiMDCQl156KUff36xj7BklY+zW7969e+zevZsdO3YwefJk1qxZw9Kl\\nSwkKCiIoKIjSpUvneKZLly7RuHFjevTowXvvvZfj72+ktLQ0IiIiuHv3Ls2aNaNBgwY4ODgQFBRE\\n8+bNCQx8+rCsML+7d++SO3duoqOjKVOmTJavlRhy8TSjpNitT3p6OlFRUVSqVIlPPvmE999/n8DA\\nQJo1a8bQoUPJk8f4Wxju3bvHqlWr6NHjbydk2Y179+6xa9cutm7dSkJCAosWLWLBggWkpqby4osv\\n4ufnZ3REu6G1pnnz5pQuXZrZs2dn6ScpKXZhFocOHWLRokWEhITg4+NDeHg4N2/exMPDAw8PD6Pj\\nARATE8Mbb7zBypUrcXNzMzqOxVq7di0hISFs3bqVMmXK8Msvv2AymWSxsxxw584dWrdujb+/P/Pm\\nzXvmIcKMFrsMwok/0Vpz5MgRZs6cCcC+ffvw9vbm559/5tChQ4/vwrSUUj979iyNGjWiXbt2UupP\\n8dJLL/Htt99y8eJF5syZg4ODAwMHDuRf//oXs2bN4tq1a0ZHtFmenp5s3LiRxMRELl26lO3vJ2fs\\n4rHFixczbdo07t27R9euXZk8ebJFX3xMS0ujWrVqvPHGGwwcONDoOFYpJSWFLVu28MMPP3Dw4EGi\\noqKIjo6mYMGCFnWLvC158OABGzZs4OWXX870vjIUI57q4sWLhISEsHv3blasWMGuXbtwdnambt26\\nFj+jQmuNUoqoqCiee+45o+PYhPT0dBwdHZkwYQIff/wxTZo0oWvXrnTu3Nni/z5Ykxs3blCzZk0m\\nT55Mt27dMrWvDMWIf/Thhx/y/PPPc/ToUQYNGoTWmkaNGlGvXj2r+J941KhRfPfdd1LqZvT7T2fj\\nx48nPj6edu3asWXLFpRS7Nmzh7i4OIMT2oYCBQqwevVq3nzzTbLrBNfy/w8WZpGcnMzChQtp0qQJ\\niYmJdO/enfj4eBYsWEBQUJBVlPnvFi1axKpVq2jVqpXRUWxW3rx56d27N19//TVKKUJDQ6lRowYd\\nO3Zk9+7dRsezelWqVGHu3Lls3749e94gI3cxmfuX3Hmas3766Sft4+Ojmzdvrjds2GDVt6NHRETo\\nggUL6uPHjxsdxe7cvXtXz5o1S/fv319r/fC/RVJSksGprF9YWFiGP0cyeOepjLHbqLCwML744gum\\nT5/OvXv3SE1NtYlhi6SkJI4fPy433FiAHj16sHXrVoKDgxk4cCBFixY1OpJV6tGjB+7u7sydO/ep\\n28oYu506dOgQdevW5ZVXXqFq1aq4u7tTpkwZmyj1Dz74gIsXL0qpW4jvvvuOXbt2kZCQwIQJE4CH\\ny9eKzPnyyy/ZtGkTO3bsMNsx5YzdBmit2bRpE+XLl8fJyYnIyEheeukli56qmFmbN29mwIABHDt2\\nzGLm0Is/S0lJ4bnnnqNWrVpMmjSJsmXLGh3Jaqxbt47PP/+czZs3/+N2csZuJ/bv30+jRo0YMWIE\\n169fp2TJkrRv396mSv3+/fsMGDCAr776Skrdgrm4uHD06FGef/556tSpw9KlS42OZDXatGnD2rVr\\nzfZwbCl2K5Wens69e/d4/fXX6d27N0eOHKF27dpGx8oWcXFxvPLKKzRv3tzoKOIpPDw8ePfddzl1\\n6hRBQUFERUUxZswYEhISjI5m8ZydnQkKCuLw4cNZPpYUu5WJi4ujd+/e9OzZk9y5c/Prr7/Sp08f\\nm13v48KFC/j7+zN16lSjo4hMyJ8/P/nz5ydv3rzcuHGDcuXKMW3aNJKSkoyOZrGUUnTr1o3+/fuT\\nnp6epWNJsVuRiRMnUqNGDUqWLMns2bMBbPqRaVprOnTowJo1a4yOIp5RkSJFmDdvHr/88gsnTpzg\\nwYMHXL169fFa8uLP+vbtS+7cuZk3b16WjiPFbuHS09P58ccf0VrTsGFDTpw4wYQJE8ibN6/R0bLd\\n9u3buX///jOtqSEsy3PPPceiRYvw8vJixowZVKlShV27dhkdy+Iopfj000/x9/fP2nFkVozlOnTo\\nEMHBwXh4eLB69Wq7KPM/atasGa+++iq9evUyOoows1WrVjFkyBC6d+/OtGnTjI5jcZKTk7lw4cL/\\nzCySWTFWLjw8nObNmzNo0CB+/vlnuyt1gPfffz/TiyQJ69C+fXuOHz9Op06dMJlMrF+/3mwzQmzB\\nzp076dix4zN/JlLsFmb79u2sXr2agIAATp48SZ8+fWx6HP3vrFq1ioCAAFxcXIyOIrKJp6cnNWvW\\n5MaNG4wbN45WrVpx4cIFo2NZhN9ngG3atOmZ9pditxD37t3jjTfeoHfv3uTKlQulFPnz5zc6liFO\\nnTpFcHCwnMHZiUKFChEWFka9evWoXr060dHRRkcynFKK0aNHM2XKlGfa3zbnyFmhgQMH4ujoyJEj\\nR/D29jY6jqFmzJjBoEGD5GYkO+Ls7My4cePo1q0bpUuXZuvWrVSsWJFixYoZHc0wnTt3pkyZMs+0\\nr5yxGygtLY0JEyZw48YN5s6dy8KFC+2+1E0mEytXrqRnz55GRxEGKFOmDEopDh8+TPXq1Vm9erXR\\nkQzj5OSEr68v+/bty/S+UuwGuXHjBi1atOCXX35BKUWuXLmMjmQRHBwcCAsLo3Tp0kZHEQYaOXIk\\na9euZfDgwSxYsMDoOIY5d+4cr732Wqb3k2I3QGpqKvXr1ycwMJBNmzbZ7Vj6k2zbts3oCMJC1K5d\\nm/DwcFq2bMmNGzfsclmCwMBAbt++zenTpzO1nxR7DgsNDcXZ2ZnNmzczdepUm1qsyxyGDBkiS7+K\\nx3x8fChSpAg//fQTNWvW5NixY0ZHylEODg60bds200NScvE0h6SkpDB8+HC2bNnCwYMHKVmypNGR\\nLM7p06e5ffu2rLcu/sfrr7+Oh4cHjRs3Zvbs2XTu3NnoSDlm1KhRmX50pZyx54DffvuNpk2bEhcX\\nR1hYmF3ebJQRa9asoW3btlb1/FWRc35/YpPJZAJ4/LutK126NLdv3+bWrVsZ3kf+D8pmycnJ5MmT\\nh759+7J69Wq8vLyMjmSxXn31VT744AOjYwgLVq1aNV555RU2btxIUFAQ169fNzpSjhg+fDihoaEZ\\n3l6KPRtt2rSJOnXq4OjoSJ8+feRM9CliY2PJly+f0TGEFXjxxRcJDAykfv36XLx40eg42e65554j\\nKioqw9tL02STtWvX0rNnT7788ksp9AwwmUw0adKEBw8eGB1FWAFHR0emTZtG7969GTNmjNFxsl35\\n8uU5depUhreX1R2zwe3btwkICOCHH36gZs2aRsexCnFxcbzwwgt2cfYlzCs1NZWbN2+SnJyMr6+v\\n0XGyxalTpzh37hwtWrSQ1R2NEBkZiaenJ8ePH5dSz4RTp05Rvnx5o2MIK+Ts7MyOHTto2LAhZ8+e\\nNTpOtihfvjxNmjTJ8PZS7Ga0ePFi2rRpw+XLl3F1dTU6jlXx8/Nj5MiRRscQVqp79+6MGzeORo0a\\nZWos2lqYTKZM3ciY5XnsSqkSwGLAB9DAXK31Z1k9rrX5+uuvef/999mxYwdFixY1Oo7VKVu2bJaf\\nGiPsW//+/XFxcSEqKornnnvO6Dhm5eDgQNGiRTM8zm6OM/Y0YITWuiJQB3hDKVXRDMe1Glprfv31\\nV37++Web+wuVU4YMGcKsWbOMjiEAliwBX19wcHj4+5IlRifKsF69etG+fXvmzJnD4cOHjY5jVplZ\\nTyrLxa61vqy1jnz0z3eBk4DdrLW5evVqTpw4wcyZM+WMMwsePHiAs7Oz0THEkiUQHAxxcaD1w9+D\\ng62q3AHy589Py5YtOXfunNFRzKZZs2YZ3tasY+xKKV+gOpDxmfRWLDw8nH79+pGenm50FKuXmpoq\\nxW4J3n0XEhP//Fpi4sPXrUinTp0YPXo07dq14969e0bHMYvp06dneFuzrRWjlMoN/AS8pbW+84Q/\\nDwaCAZtYJ+Xy5cu8/PLLzJ07lypVqhgdx+pVq1bNrh+qYDHi4zP3ugUbOnQoTk5ONrP0wLBhwzK8\\nrVnmsSulnIF1wGat9SdP294W5rGHh4ezZ88e3nrrLaOjCGE+vr4Ph1/+qlQpsNJhjfj4eDZs2MCA\\nAQOMjpIlAQEBREZG5sw8dvXwSctfAyczUurWTmvN0qVLqV69upS6GX3zzTesWLHC6Bjiww/B3f3P\\nr7m7P3zdSrm5uTFlyhRCQkKMjpIlycnJGd7WHGPs9YBXgSZKqcOPfrUyw3Et0scff8xHH30kt76b\\n2Y0bN9i9e7fRMcS//w1z5z48Q1fq4e9z5z583UoVKlSI1atX88Ybb3Do0CGj4zyzmzdvZnjbLI+x\\na633ACqrx7EGGzZs4JNPPiE0NBT3v57ViCx57rnn2LFjh9ExBDwscSsu8iepVq0ac+bMserVIC9d\\nupThB/PIgzYyYdeuXSxfvpwSJUoYHcXmlC9fnngrvEAnrEeHDh3QWrNo0SL+/e9/4+RkPfV35swZ\\njh8/nuHtreffzEAmk4mYmBimTZtmdBSb5e/vz9GjR42OIWyc1prFixdz48YNRowYYXScDNuxYwdh\\nYWEZ3l7WismABQsW0Lt3b4xYCdNeKKVYtmwZFy5cMDqKsGEODg7MmTOHKVOmEBMTY3ScDMvsInlS\\n7E9x+fJlxowZw+zZs3k

In [110]:
with open('filepaths.txt', 'w') as filehandle:
    for i in filepaths:
        filehandle.write(f'{i}\n')

In [158]:
repo_list[1].get_contents(filepaths[1][6].path)

ContentFile(path="Lab02/staff.ipynb")

In [121]:
filepaths[1][1].path

'README.md'

In [328]:
filepaths[0][0].path

'.DS_Store'

In [128]:
repo_list

[Repository(full_name="ds-modules/core-resources"),
 Repository(full_name="ds-modules/ENGIN-7"),
 Repository(full_name="ds-modules/DS-Modules"),
 Repository(full_name="ds-modules/ISF-189"),
 Repository(full_name="ds-modules/EDUC-223B"),
 Repository(full_name="ds-modules/NESTUD-190A"),
 Repository(full_name="ds-modules/ETHSTD-21AC"),
 Repository(full_name="ds-modules/XRHETOR-R1A"),
 Repository(full_name="ds-modules/HIST-88"),
 Repository(full_name="ds-modules/GWS-101"),
 Repository(full_name="ds-modules/ART-W23AC"),
 Repository(full_name="ds-modules/IAS-150"),
 Repository(full_name="ds-modules/SOC-130AC"),
 Repository(full_name="ds-modules/INFO-290"),
 Repository(full_name="ds-modules/GWS-131"),
 Repository(full_name="ds-modules/LINGUIS-110"),
 Repository(full_name="ds-modules/PSYCH-167AC"),
 Repository(full_name="ds-modules/XENGLIS-31AC"),
 Repository(full_name="ds-modules/ECON-101B"),
 Repository(full_name="ds-modules/LS-88"),
 Repository(full_name="ds-modules/RDM-DeCal"),
 Repository(full_name="ds-modules/EPS-C20"),
 Repository(full_name="ds-modules/COGSCI-1B"),
 Repository(full_name="ds-modules/MCB-288"),
 Repository(full_name="ds-modules/SPORTS"),
 Repository(full_name="ds-modules/IB-ESPM-105"),
 Repository(full_name="ds-modules/ENVECON-100"),
 Repository(full_name="ds-modules/CUNEIF-102A"),
 Repository(full_name="ds-modules/Module-Feedback"),
 Repository(full_name="ds-modules/MEDST-250"),
 Repository(full_name="ds-modules/HIST-283"),
 Repository(full_name="ds-modules/LEGALST-190"),
 Repository(full_name="ds-modules/HTRC-Uncamp"),
 Repository(full_name="ds-modules/PACS-190"),
 Repository(full_name="ds-modules/examples"),
 Repository(full_name="ds-modules/R-Module"),
 Repository(full_name="ds-modules/IAS-106"),
 Repository(full_name="ds-modules/nbinteract-image"),
 Repository(full_name="ds-modules/PH-142"),
 Repository(full_name="ds-modules/E-157AC"),
 Repository(full_name="ds-modules/MCB-32"),
 Repository(full_name="ds-modules/HIST-160"),
 Repository(full_name="ds-modules/curriculum-guide"),
 Repository(full_name="ds-modules/EEP-147"),
 Repository(full_name="ds-modules/ESPM-163ac"),
 Repository(full_name="ds-modules/EPS-130"),
 Repository(full_name="ds-modules/MCB-163L"),
 Repository(full_name="ds-modules/CE-110"),
 Repository(full_name="ds-modules/ES-21AC-SP19"),
 Repository(full_name="ds-modules/FRENCH-43"),
 Repository(full_name="ds-modules/ECON-141"),
 Repository(full_name="ds-modules/SOC-5"),
 Repository(full_name="ds-modules/CP-101-student"),
 Repository(full_name="ds-modules/modules-textbook"),
 Repository(full_name="ds-modules/CP101BigData"),
 Repository(full_name="ds-modules/EDUC-W142"),
 Repository(full_name="ds-modules/POLSCI-3"),
 Repository(full_name="ds-modules/featured-modules"),
 Repository(full_name="ds-modules/COGSCI-1"),
 Repository(full_name="ds-modules/LS-22"),
 Repository(full_name="ds-modules/surveydata"),
 Repository(full_name="ds-modules/POLSCI-5"),
 Repository(full_name="ds-modules/SW-282"),
 Repository(full_name="ds-modules/EEP102"),
 Repository(full_name="ds-modules/CP-113B"),
 Repository(full_name="ds-modules/Bio-1B"),
 Repository(full_name="ds-modules/CP-113A"),
 Repository(full_name="ds-modules/colwrit-r4b"),
 Repository(full_name="ds-modules/Library"),
 Repository(full_name="ds-modules/PH150E-CP117AC"),
 Repository(full_name="ds-modules/SOC-5-Fall19"),
 Repository(full_name="ds-modules/Legalst-123"),
 Repository(full_name="ds-modules/EEP-147-SP20"),
 Repository(full_name="ds-modules/ECON-141-SP20"),
 Repository(full_name="ds-modules/EPS-130-SP20"),
 Repository(full_name="ds-modules/EPS-115-SP20"),
 Repository(full_name="ds-modules/course-assets"),
 Repository(full_name="ds-modules/MCB-50"),
 Repository(full_name="ds-modules/espm-c167"),
 Repository(full_name="ds-modules/EPS-118-SP20"),
 Repository(full_name="ds-modules/textbook"),
 Repository(full_name="ds-modules/ES-21AC-sp20"),
 Repository(full_name="ds-modules/ds-modules.github.io"),
 Repository(full_name="ds-modules/BUDS-su20"),
 Repository(full_name="ds-modules/workshop-su20"),
 Repository(full_name="ds-modules/POLSCI3-FA20"),
 Repository(full_name="ds-modules/MCB-140"),
 Repository(full_name="ds-modules/IB-105-ESPM-125-fa20"),
 Repository(full_name="ds-modules/ENVECON-118-FA20"),
 Repository(full_name="ds-modules/COGSCI-131-FA20"),
 Repository(full_name="ds-modules/COGSCI-C131-PSYCH-123-FA20"),
 Repository(full_name="ds-modules/EPS256-FA20"),
 Repository(full_name="ds-modules/modules-ipynb-workshop"),
 Repository(full_name="ds-modules/data-4ac"),
 Repository(full_name="ds-modules/POLSCI3-Fa20-Dev"),
 Repository(full_name="ds-modules/Infodemiology-Projects"),
 Repository(full_name="ds-modules/ps-106a"),
 Repository(full_name="ds-modules/GS102-SurveyData-FA20"),
 Repository(full_name="ds-modules/Infodemiology-Mental-Health"),
 Repository(full_name="ds-modules/Infodemiology-Nutrition"),
 Repository(full_name="ds-modules/Infodemiology-Pregnancy"),
 Repository(full_name="ds-modules/DATA198-SP21.github.io"),
 Repository(full_name="ds-modules/HCE-Materials"),
 Repository(full_name="ds-modules/DATA-198-SP21"),
 Repository(full_name="ds-modules/Econ-172-Sp21"),
 Repository(full_name="ds-modules/EPS-130-SP21"),
 Repository(full_name="ds-modules/PS-88-21-DEV"),
 Repository(full_name="ds-modules/ECON-140-SP21"),
 Repository(full_name="ds-modules/IB-161-SP21"),
 Repository(full_name="ds-modules/EEP-147-SP21"),
 Repository(full_name="ds-modules/CP-101-SP21"),
 Repository(full_name="ds-modules/Colab-data-8"),
 Repository(full_name="ds-modules/BUDS-SU21-Dev"),
 Repository(full_name="ds-modules/SOC-88-SP21"),
 Repository(full_name="ds-modules/ES-21AC-SP21"),
 Repository(full_name="ds-modules/ES-21AC-SP21-key"),
 Repository(full_name="ds-modules/Spanish"),
 Repository(full_name="ds-modules/music-30"),
 Repository(full_name="ds-modules/Deepnote-demo"),
 Repository(full_name="ds-modules/infodem-covid-babies"),
 Repository(full_name="ds-modules/infodem-mental-health"),
 Repository(full_name="ds-modules/sather-tower"),
 Repository(full_name="ds-modules/BUDS-su21"),
 Repository(full_name="ds-modules/BLDAP-Su21-student"),
 Repository(full_name="ds-modules/ENVECON-118-FA21"),
 Repository(full_name="ds-modules/ART-23AC-FA21"),
 Repository(full_name="ds-modules/ECON-140-FA21"),
 Repository(full_name="ds-modules/IB-105-ESPM-125-FA21"),
 Repository(full_name="ds-modules/global-fa21"),
 Repository(full_name="ds-modules/air-quality"),
 Repository(full_name="ds-modules/DATA88-SP22"),
 Repository(full_name="ds-modules/data8-esp"),
 Repository(full_name="ds-modules/EPS-130-SP22"),
 Repository(full_name="ds-modules/MECENG-103"),
 Repository(full_name="ds-modules/ECON-143-SP22"),
 Repository(full_name="ds-modules/ECON-140-SP22"),
 Repository(full_name="ds-modules/GLOBAL-88-SP22"),
 Repository(full_name="ds-modules/Data198-SP22"),
 Repository(full_name="ds-modules/ESPM-109E-SP22"),
 Repository(full_name="ds-modules/IB-C32"),
 Repository(full_name="ds-modules/ETHSTD-21AC-SP22"),
 Repository(full_name="ds-modules/EEP-147-SP22"),
 Repository(full_name="ds-modules/ECON-172-SP22"),
 Repository(full_name="ds-modules/sample-intro-notebooks"),
 Repository(full_name="ds-modules/datahub-homepage"),
 Repository(full_name="ds-modules/ECON-140-SU22"),
 Repository(full_name="ds-modules/BUDS-SU22"),
 Repository(full_name="ds-modules/LEGAL-190-FA22"),
 Repository(full_name="ds-modules/polisci-3"),
 Repository(full_name="ds-modules/PUBPOL-ETHSTD-C164A-SP23"),
 Repository(full_name="ds-modules/materials-x22"),
 Repository(full_name="ds-modules/EPS88-24031-FA22"),
 Repository(full_name="ds-modules/ECON-140-FA22-SB"),
 Repository(full_name="ds-modules/ECON-140-FA22-RDE"),
 Repository(full_name="ds-modules/Library-Data-Workshop-Fall-2022"),
 Repository(full_name="ds-modules/ENVECON-118-FA22"),
 Repository(full_name="ds-modules/ECON-130-FA22"),
 Repository(full_name="ds-modules/CIVENG-190"),
 Repository(full_name="ds-modules/CalTeach-FA22"),
 Repository(full_name="ds-modules/ECON-148"),
 Repository(full_name="ds-modules/CE200B"),
 Repository(full_name="ds-modules/ENVECON-118-SP23"),
 Repository(full_name="ds-modules/EPS130-21521-SP23"),
 Repository(full_name="ds-modules/ECON-140-SP23-SB"),
 Repository(full_name="ds-modules/PS88-SP23-Public"),
 Repository(full_name="ds-modules/DATA198-SP23"),
 Repository(full_name="ds-modules/Search-Engine"),
 Repository(full_name="ds-modules/E7"),
 Repository(full_name="ds-modules/EEP-147-SP23"),
 Repository(full_name="ds-modules/ECON-172-SP23")]

In [228]:
repo_list[1].get_contents(filepaths[1][16].path).content

''

In [249]:
for i in range(len(filepaths)):
    for j in range(len(filepaths[i])):
        if filepaths[i][j].path == 'xenglish-r1a/drafts/text_draft.ipynb':
            print(i, j)

57 136

In [333]:
repo_list[1].get_contents(filepaths[1][6].path).decoded_content

b'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "collapsed": true\n   },\n   "source": [\n    "# E7: Introduction to Computer Programming for Scientists and Engineers"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Lab Assignment 2"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "For each question, you will have to fill in one or more Python functions. We provide an autograder with a number of test cases that you can use to test your function. Note that the fact that your function works for all test cases thus provided does necessarily guarantee\\n",\n    "that it will work for all possible test cases relevant to the question. It is your responsibility\\n",\n    "to test your function thoroughly, to ensure that it will also work in situations not covered\\n",\n    "by the test cases provided"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 1,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "# Please run this cell, and do not modify the contets\\n",\n    "import math\\n",\n    "import numpy as np\\n",\n    "import matplotlib.pyplot as plt\\n",\n    "np.seterr(all=\'ignore\');\\n",\n    "# %run lab2_ag.py"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 1\\n",\n    "\\n",\n    "Write a Python function that calculates the roots of a quadratic equation $ax^2+bx+\\n",\n    "c = 0$ of unknown $x$, using the quadratic formula below. \\n",\n    "\\n",\n    "$$x = \\\\frac{-b\\\\pm \\\\sqrt{b^2-4ac}}{2a}$$"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "The function output should be a two element tuple. The first element should be the root computed by setting the $\\\\pm$ to $+$, and the second element should be the root computed by setting the $\\\\pm$ to $-$. You may assume $b2 - 4ac \\\\ge 0$."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 2,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def solve_quadratic(a, b, c):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> solve_quadratic(1, -7, 10)\\n",\n    "    (5.0, 2.0)\\n",\n    "    >>> solve_quadratic(5, -23, 2)\\n",\n    "    (4.511334438749598, 0.08866556125040184)\\n",\n    "    \\"\\"\\"\\n",\n    "    disc = math.sqrt(b*b-4.*a*c)\\n",\n    "    return (-b+disc)/(2.*a), (-b-disc)/(2.*a)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 2\\n",\n    "\\n",\n    "Write a Python function that computes the Euclidean distances between two sets of\\n",\n    "points. The x-coordinates for the first set of points will be stored in a column vector\\n",\n    "`X_1`, the y-coordinates for the first set of points in `Y_1`, the x-coordinates for the second\\n",\n    "set of points will be stored in a column vector `X_2`, the y-coordinates for the second\\n",\n    "set of points in `Y_2`. `X_1`, `Y_1`, `X_2`, and `Y_2` are $N$ by $1$ arrays where $N$ is the number\\n",\n    "of points in each set. Note that, for a single pair of points, $(x_1, y_1)$ and $(x_2, y_2)$, the\\n",\n    "Euclidean distance can be obtained from the distance formula:\\n",\n    "\\n",\n    "$$ \\\\text{Euclidean distance} = \\\\sqrt{(x_1-x_2)^2 + (y_1-y_2)^2} $$"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 3,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def euclidean_distance(x1, y1, x2, y2):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> euclidean_distance(np.array([0,0]),np.array([0,0]),np.array([3,5]),np.array([4,12]))\\n",\n    "    array([  5.,  13.])\\n",\n    "    \\"\\"\\"\\n",\n    "    x = x1 - x2\\n",\n    "    y = y1 - y2\\n",\n    "    return np.sqrt(x*x+y*y)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 3\\n",\n    "\\n",\n    "Carbon dating is a method for determining the age of an object containing the ra-\\n",\n    "dioisotope carbon-14. Since carbon-14 is subject to radioactive decay, the number of\\n",\n    "carbon-14 atoms in a sample will decay over time according to the following exponential\\n",\n    "decay law:\\n",\n    "\\n",\n    "$$ N(t) = N_0 e^{-\\\\lambda t} $$\\n",\n    "\\n",\n    "where $N_0$ is the number of atoms of the isotope in the original sample, $N(t)$ is the remaining number of atoms after a time $t$, $\\\\lambda$ is the expoential decay constant and $t$ is the time.\\n",\n    "\\n",\n    "Write a function that calculates the remaining fraction of carbon-14 in a sample after\\n",\n    "a certain amount of time (in years). The remaining fraction is defined as the ratio of\\n",\n    "the number of atoms at the present time ($N(t)$) to the initial number of atoms ($N_0$).\\n",\n    "You can re-arrange the decay formula above to find an expression for this ratio.\\n",\n    "\\n",\n    "Assume $\\\\lambda = 0.00012097 \\\\: \\\\text{years}^{-1}$."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 4,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def c14_dating(time):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> c14_dating(10000)\\n",\n    "    0.29828675203393595\\n",\n    "    >>> c14_dating(5730)\\n",\n    "    0.49999454030978113\\n",\n    "    \\"\\"\\"\\n",\n    "    return math.e**(-time*0.00012097)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 4\\n",\n    "\\n",\n    "A ball is launched in the air with initial velocity $v_o$ from an initial position of coordinates $(x_0, y_0)$ as illustrated below: \\n",\n    "\\n",\n    "<img src=\\"resources/E7_Lab2_1.jpg\\" style=\\"width: 300px;\\"/>\\n",\n    "<center>*Figure 1: Ball launching at angle $\\\\theta$ from the x-axis with inital velocity $v_0$*</center>\\n",\n    "\\n",\n    "The ball is launched at an angle $\\\\theta$ (expressed in degrees) from the x-axis. The\\n",\n    "equations describing the motion (i.e. the position of the ball $(x(t), y(t)$) as a function\\n",\n    "of time $t$) of the ball are:\\n",\n    "\\n",\n    "$$ x(t) = x_0 + v_0 t \\\\cos(\\\\theta) $$\\n",\n    "$$ y(t) = y_0 + v_0 t \\\\sin(\\\\theta) - \\\\frac{1}{2}gt^2 $$\\n",\n    "\\n",\n    "where $g$ is the gravitational acceleration ($g = 9.81 m s^22$). Since $\\\\theta$ is given in degrees,\\n",\n    "you will want to convert it first into radians before using the `sin` or `cos` functions."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "a. Write a function that calculates the time at which the ball reaches the ground.\\n",\n    "\\n",\n    "Note that when the ball hits the ground, $y = 0$. Also, before writing your code,\\n",\n    "don\'t forget to use pen and paper to manipulate the equation(s) above and get a\\n",\n    "mathematical expression for time."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 5,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "# run this cell to create a global variable g, but make sure you don\'t have any other global variables also named g\\n",\n    "g = 9.81"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 6,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def proj_time(y0, v0, theta):\\n",\n    "    \\"\\"\\"\\n",\n    "    >>> proj_time(0, 15, 40)\\n",\n    "    1.9657113446071535\\n",\n    "    \\"\\"\\"\\n",\n    "    b = v0 * math.sin(np.deg2rad(theta))\\n",\n    "    time = -(-b - math.sqrt(b**2+2.*g*y0))/g\\n",\n    "    return time"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "b. Write a function that calculates the horizontal distance traveled by the ball before\\n",\n    "it reaches the ground. You can use the function `proj_time` and the equations of\\n",\n    "motion."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 7,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def proj_distance(y0, v0, theta):\\n",\n    "        \\"\\"\\"\\n",\n    "        >>> proj_distance(0, 15, 40)\\n",\n    "        22.587333784683665\\n",\n    "        \\"\\"\\"\\n",\n    "        time = proj_time(y0, v0, theta)\\n",\n    "        dist = v0 * time * math.cos(np.deg2rad(theta))\\n",\n    "        return dist"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "## Question 5\\n",\n    "\\n",\n    "Cell towers and triangulation. Note that part 5b will rely on the function you develop\\n",\n    "in part 5a."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "a. Write a function that draws a circle centered at the point of coordinates $(x_c, y_c)$\\n",\n    "and with radius $r_c$."\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "Your function should return nothing, but it should plot a circle with a dashed black\\n",\n    "line for the perimeter and a red point for the center. Multiple function calls, along\\n",\n    "with the command hold on should plot multiple circles. For example, the code:\\n",\n    "\\n",\n    "```PYTHON\\n",\n    "fig, ax = plt.subplots()\\n",\n    "ax.set_xlim((-5,5))\\n",\n    "ax.set_ylim((-5,5))\\n",\n    "draw_circle(ax, 0, 0, 4)\\n",\n    "draw_circle(ax, 2, 2, 3)\\n",\n    "plt.show()\\n",\n    "```\\n",\n    "\\n",\n    "should plot something similar to Figure 2 here:\\n",\n    "\\n",\n    "<img src=\\"resources/E7_Lab5_1.jpg\\" style=\\"width: 500px;\\"/>\\n",\n    "<center>*Figure 2*</center>\\n",\n    "\\n",\n    "Don\'t worry about making the plot look exactly like Figure 2."\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 46,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": [\n    "def draw_circle(ax, xc, yc, rc):\\n",\n    "    circle = plt.Circle((xc, yc), rc, fill=False, linestyle=\'--\')\\n",\n    "    ax.plot((xc), (yc), \'o\', color = \'red\')\\n",\n    "    ax.add_artist(circle)\\n",\n    "    # plt.show()"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 47,\n   "metadata": {},\n   "outputs": [\n    {\n     "data": {\n      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXYAAAD8CAYAAABjAo9vAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\\nAAALEgAACxIB0t1+/AAAIABJREFUeJzt3XdcVnX/x/HXly0oggu3oKI5coErb7fkTM2VepsrJTW1\\n1DQ1s241R/4qs7QcmVqWkrn3Ss0FApoTByC4VzgBGdf394fmXd2WIBeca3yej4cP4/Kcc727sjeH\\n7/me71Faa4QQQtgOB6MDCCGEMC8pdiGEsDFS7EIIYWOk2IUQwsZIsQshhI2RYhdCCBsjxS6EEDZG\\nil0IIWyMFLsQQtgYJyPetECBAtrX19eItxbC5mmtUUpx584dkpKSSEtLA6BYsWLcvHmT69evk5aW\\nRnp6Ov7+/gCcOXMGAKUUPj4++Pj4EBUVRWpqKlprcuXKhb+/P+fPn+fatWs4ODjg6OhIxYoVSU5O\\n5sqVKzg5OeHo6Ej+/Plxd3fnzp07uLi44OrqilLKsM/DlkRERNzQWhd82naGFLuvry/h4eFGvLUQ\\nVs9kMhEdHc2pU6eoUKECxYoVo3v37sTExBAbG0uHDh345ptv+OCDD7h9+zb58+fHx8eH/v37Exsb\\ny+XLl/H29sbLy4uCBQvi5JS5GjCZTNy7d4+EhASKFy/O9evX2b9/P7du3SIhIYFmzZrh7+9P27Zt\\niY2N5cyZM/Tp04evvvqKadOmkZiYiJ+fH6VLl6ZBgwbZ9CnZJqVUXIa2M2KtmMDAQC3FLsTTpaen\\nc/r0aSIiInjppZc4evQorVu3xsvLiwoVKjBy5EiaNGnCypUr8fX1xc/PD29vb6Nj/0l6ejr379/H\\n09OTlStXcvjwYWJiYkhOTubHH3/ks88+Y/fu3dSoUYMaNWrQuHFj3NzcjI5tkZRSEVrrwKduJ8Uu\\nhOWIj48nLCyMTp06MW/ePIYPH46Pjw81atTg//7v/yhYsCCJiYnkz5/f6KhmEx8fz759+4iMjCQi\\nIoLly5cTERHB559/TkBAALVq1aJBgwa4u7sbHdVwUuxCWIHU1FScnZ2ZNWsWM2fO5LfffqNJkyZ8\\n//33JCQk4OTkhJeXl9Exc9z169fZuXMnERER7Nu3jwkTJlCpUiXmz59PUFAQ1atXx9HR0eiYOU6K\\nXQgLFRoayoYNG9i2bRt37tzh6NGjHDhwAFdXV6pWrYqDg0xWe5KLFy/y0UcfsW3bNq5cucLcuXPp\\n2LEj8fHxlCxZ0uh4OUKKXQgLkZqaytatW7lw4QLBwcGMHDkSBwcHgoKCqFevHrly5TI6otW5ePEi\\nzs7OODo6UqlSJfLmzcsrr7xCr169KFOmjNHxsk1Gi92QWTFC2IsxY8Ywf/58ypUrx2uvvQbA9OnT\\nDU5l/YoVK/b4ny9fvszBgwdZunQpBw4cwM/Pj88//5z27dtTqlQpA1MaR4pdCDPRWnPw4EF++OEH\\nbt26xTfffEOjRo0YMGCA3RZMTlBKUatWLWrVqgXAnTt3OHHiBBMnTqRcuXK89957tGzZ0uCUOUsG\\n84TIot+HM1u0aEGPHj3w9PTknXfeAaB58+ZS6jnM09OTOXPmcOnSJcaNG0e+fPlITEykW7dubN++\\nHXt4HKicsQvxjKKjo/n88885evQo27dvZ/HixRQqVEjusrQQLi4utGrVCoDk5GQaN27Mm2++iVKK\\nzz//nEaNGhkbMBvJGbsQz2D06NHUqVMHNzc3vvnmGwB8fHyk1C2Um5sbwcHBHD16lBkzZuDj48PV\\nq1cZM2YM58+fNzqe2UmxC5EBKSkpzJ8/n+bNm5Oamkq/fv2Ii4tj6tSpdjPVzhYopWjatCkVKlQA\\nICkpiapVq9KlSxdOnz5tcDrzkWIX4im2bdtGhQoVCAkJYdSoUTg5OVG2bFm5E9LK+fj4MGPGDM6d\\nO8e//vUv3NzcOH/+PCdPnjQ6WpZJsQvxBFprNm7cyN27d8mXLx/z589ny5YtNG3aVIZbbIynpydD\\nhw6lZMmSHDlyhAYNGvDaa69Z9RCNFLsQf7F//34aNWrEiBEjiI+Pf7wwlbB9rVu35syZM/j4+NCg\\nQQMePHhgdKRnIsUuxB/ExcXRvXt3evfuzZEjR6hUqZLRkUQO8/LyYvLkyURFReHq6kqvXr2YNGkS\\niYmJRkfLMCl2YfeSkpIYN24c7777LqVKleLs2bP06dMn0+uUC9vi6uoKwHvvvceRI0eoXLky27Zt\\nMzhVxpit2JVSjkqpQ0qpdeY6phDZbfv27VSpUoXTp08zePBgALtcNVD8vbJlyxISEsLs2bO5ceMG\\nWmt+++03o2P9I3Oesb8JWP/lZGEXUlNTAYiIiGDGjBmEhIRQpEgRg1MJS9aiRQu6du3KsWPHqFCh\\nAkuWLLHYu1jNUuxKqeJAa2C+OY4nRHbaunUr5cuX59y5c4waNYrWrVsbHUlYkeeff57169czefJk\\nOnTowN27d42O9D/MNYg4AxgF5DHT8YQwC5PJxN27d0lMTCRfvny89tprbNmyhf79+7N//368vb1J\\nTk5mw4YNpKeno7WmVq1aVK1alWXLlpGWloajoyOFChWiSZMmxMTEkJSUhLe3N97e3ri5ucn0RzsU\\nGBhIZGQkCxYswMPDg1u3blnUA1GyXOxKqTbANa11hFKq0T9sFwwEA3KnnnhmWmuuX79ObGwssbGx\\n1KtXDw8PD9555x0SEhK4desWzZs3Z+TIkdSrV4/Q0FDc3d2pVKkSmzdv5sqVKwQGBnL69Gmio6Op\\nX78+iYmJ7Nq1C0dHR5RSFC9enKpVq7Jjxw7u3r2LyWTC39+fJk2asGjRIn788cfH73XlyhV27drF\\nqFGj8PLywtvbmzFjxlC7dm3+85//UKhQIfz8/KhcubJNrxNuj1xdXRk4cCBaa5o0aULbtm0ZP368\\nRTwoJcsP2lBKTQFeBdIAN8ATWKG17vF3+8iDNsQ/SUlJwcXFhf379xMaGkpMTAznzp1j+fLlfP/9\\n94wYMQI/Pz/8/PwYO3Ys5cuX57vvvntcrKVLl6ZMmTLcuXMHd3d39u/fz9SpU1mzZk22XBi9d+8e\\n58+ff1z2VapUIX/+/HzyySdcuXKF2NhYatWqxfjx42nRogW//fYbfn5+PP/884wbN474+HhSU1Mp\\nWbIkzs7OZs8nst+VK1fo3LkzXl5efPvtt9l29m7IE5QenbG/rbVu80/bSbELeFjg9+/fx9vbm5Ej\\nR7J3717OnDlDuXLl2Lt3L7Nnz+bkyZOULl0aPz8/WrVqhbOzc4aHPrTWfPHFF0yaNIlFixbRokWL\\nbP43erqrV68SExNDbGwsd+/e5fXXX2fmzJl8+umnXLp0icKFC7N7924cHBwICwujRo0a+Pr6ynCP\\nFUhJSWHs2LH07duXihUrZst7ZLTY0Vqb7RfQCFj3tO0CAgK0sC/Jycn6/v37+tatWzo4OFgHBgbq\\nXLly6ffee09rrfX333+vd+7cqS9fvqxNJpNZ3jMyMlJXq1ZNR0dHm+V42S0lJUVHR0frtLQ0HR4e\\nrl966SVdtGhR7e3trTdu3KgfPHigly5dqk+fPq3T09ONjiv+wZtvvqlDQkLMflwgXGekizOykbl/\\nSbHbNpPJpE0mkz558qR+7bXXdPXq1XWuXLn0smXLdGpqqp45c6beu3evvnfvXra8/9WrV/XixYu1\\n1lqnpaVly3vkpMuXL+vbt2/rq1ev6vbt2+uSJUvqvHnz6k8++URrrfXGjRv1pUuXDE4p/igiIkKX\\nKlVKjx8/3mwnKlpnvNjl1jphFteuXWPTpk1s3bqVbdu2sWnTJry8vKhRowb9+/enSpUqjx/aPGTI\\nkGzLcfnyZZo1a0anTp0A27jZqHDhwsDDxapWrlwJwPXr1x/PxV+0aBGbN2+mWLFivPbaa7z11luY\\nTCaLuIhnr2rUqMHBgwcJCgoiMDCQl156KUff36xj7BklY+zW7969e+zevZsdO3YwefJk1qxZw9Kl\\nSwkKCiIoKIjSpUvneKZLly7RuHFjevTowXvvvZfj72+ktLQ0IiIiuHv3Ls2aNaNBgwY4ODgQFBRE\\n8+bNCQx8+rCsML+7d++SO3duoqOjKVOmTJavlRhy8TSjpNitT3p6OlFRUVSqVIlPPvmE999/n8DA\\nQJo1a8bQoUPJk8f4Wxju3bvHqlWr6NHjbydk2Y179+6xa9cutm7dSkJCAosWLWLBggWkpqby4osv\\n4ufnZ3REu6G1pnnz5pQuXZrZs2dn6ScpKXZhFocOHWLRokWEhITg4+NDeHg4N2/exMPDAw8PD6Pj\\nARATE8Mbb7zBypUrcXNzMzqOxVq7di0hISFs3bqVMmXK8Msvv2AymWSxsxxw584dWrdujb+/P/Pm\\nzXvmIcKMFrsMwok/0Vpz5MgRZs6cCcC+ffvw9vbm559/5tChQ4/vwrSUUj979iyNGjWiXbt2UupP\\n8dJLL/Htt99y8eJF5syZg4ODAwMHDuRf//oXs2bN4tq1a0ZHtFmenp5s3LiRxMRELl26lO3vJ2fs\\n4rHFixczbdo07t27R9euXZk8ebJFX3xMS0ujWrVqvPHGGwwcONDoOFYpJSWFLVu28MMPP3Dw4EGi\\noqKIjo6mYMGCFnWLvC158OABGzZs4OWXX870vjIUI57q4sWLhISEsHv3blasWMGuXbtwdnambt26\\nFj+jQmuNUoqoqCiee+45o+PYhPT0dBwdHZkwYQIff/wxTZo0oWvXrnTu3Nni/z5Ykxs3blCzZk0m\\nT55Mt27dMrWvDMWIf/Thhx/y/PPPc/ToUQYNGoTWmkaNGlGvXj2r+J941KhRfPfdd1LqZvT7T2fj\\nx48nPj6edu3asWXLFpRS7Nmzh7i4OIMT2oYCBQqwevVq3nzzTbLrBNfy/w8WZpGcnMzChQtp0qQJ\\niYmJdO/enfj4eBYsWEBQUJBVlPnvFi1axKpVq2jVqpXRUWxW3rx56d27N19//TVKKUJDQ6lRowYd\\nO3Zk9+7dRsezelWqVGHu3Lls3749e94gI3cxmfuX3Hmas3766Sft4+Ojmzdvrjds2GDVt6NHRETo\\nggUL6uPHjxsdxe7cvXtXz5o1S/fv319r/fC/RVJSksGprF9YWFiGP0cyeOepjLHbqLCwML744gum\\nT5/OvXv3SE1NtYlhi6SkJI4fPy433FiAHj16sHXrVoKDgxk4cCBFixY1OpJV6tGjB+7u7sydO/ep\\n28oYu506dOgQdevW5ZVXXqFq1aq4u7tTpkwZmyj1Dz74gIsXL0qpW4jvvvuOXbt2kZCQwIQJE4CH\\ny9eKzPnyyy/ZtGkTO3bsMNsx5YzdBmit2bRpE+XLl8fJyYnIyEheeukli56qmFmbN29mwIABHDt2\\nzGLm0Is/S0lJ4bnnnqNWrVpMmjSJsmXLGh3Jaqxbt47PP/+czZs3/+N2csZuJ/bv30+jRo0YMWIE\\n169fp2TJkrRv396mSv3+/fsMGDCAr776Skrdgrm4uHD06FGef/556tSpw9KlS42OZDXatGnD2rVr\\nzfZwbCl2K5Wens69e/d4/fXX6d27N0eOHKF27dpGx8oWcXFxvPLKKzRv3tzoKOIpPDw8ePfddzl1\\n6hRBQUFERUUxZswYEhISjI5m8ZydnQkKCuLw4cNZPpYUu5WJi4ujd+/e9OzZk9y5c/Prr7/Sp08f\\nm13v48KFC/j7+zN16lSjo4hMyJ8/P/nz5ydv3rzcuHGDcuXKMW3aNJKSkoyOZrGUUnTr1o3+/fuT\\nnp6epWNJsVuRiRMnUqNGDUqWLMns2bMBbPqRaVprOnTowJo1a4yOIp5RkSJFmDdvHr/88gsnTpzg\\nwYMHXL169fFa8uLP+vbtS+7cuZk3b16WjiPFbuHS09P58ccf0VrTsGFDTpw4wYQJE8ibN6/R0bLd\\n9u3buX///jOtqSEsy3PPPceiRYvw8vJixowZVKlShV27dhkdy+Iopfj000/x9/fP2nFkVozlOnTo\\nEMHBwXh4eLB69Wq7KPM/atasGa+++iq9evUyOoows1WrVjFkyBC6d+/OtGnTjI5jcZKTk7lw4cL/\\nzCySWTFWLjw8nObNmzNo0CB+/vlnuyt1gPfffz/TiyQJ69C+fXuOHz9Op06dMJlMrF+/3mwzQmzB\\nzp076dix4zN/JlLsFmb79u2sXr2agIAATp48SZ8+fWx6HP3vrFq1ioCAAFxcXIyOIrKJp6cnNWvW\\n5MaNG4wbN45WrVpx4cIFo2NZhN9ngG3atOmZ9pditxD37t3jjTfeoHfv3uTKlQulFPnz5zc6liFO\\nnTpFcHCwnMHZiUKFChEWFka9evWoXr060dHRRkcynFKK0aNHM2XKlGfa3zbnyFmhgQMH4ujoyJEj\\nR/D29jY6jqFmzJjBoEGD5GYkO+Ls7My4cePo1q0bpUuXZuvWrVSsWJFixYoZHc0wnTt3pkyZMs+0\\nr5yxGygtLY0JEyZw48YN5s6dy8KFC+2+1E0mEytXrqRnz55GRxEGKFOmDEopDh8+TPXq1Vm9erXR\\nkQzj5OSEr68v+/bty/S+UuwGuXHjBi1atOCXX35BKUWuXLmMjmQRHBwcCAsLo3Tp0kZHEQYaOXIk\\na9euZfDgwSxYsMDoOIY5d+4cr732Wqb3k2I3QGpqKvXr1ycwMJBNmzbZ7Vj6k2zbts3oCMJC1K5d\\nm/DwcFq2bMmNGzfsclmCwMBAbt++zenTpzO1nxR7DgsNDcXZ2ZnNmzczdepUm1qsyxyGDBkiS7+K\\nx3x8fChSpAg//fQTNWvW5NixY0ZHylEODg60bds200NScvE0h6SkpDB8+HC2bNnCwYMHKVmypNGR\\nLM7p06e5ffu2rLcu/sfrr7+Oh4cHjRs3Zvbs2XTu3NnoSDlm1KhRmX50pZyx54DffvuNpk2bEhcX\\nR1hYmF3ebJQRa9asoW3btlb1/FWRc35/YpPJZAJ4/LutK126NLdv3+bWrVsZ3kf+D8pmycnJ5MmT\\nh759+7J69Wq8vLyMjmSxXn31VT744AOjYwgLVq1aNV555RU2btxIUFAQ169fNzpSjhg+fDihoaEZ\\n3l6KPRtt2rSJOnXq4OjoSJ8+feRM9CliY2PJly+f0TGEFXjxxRcJDAykfv36XLx40eg42e65554j\\nKioqw9tL02STtWvX0rNnT7788ksp9AwwmUw0adKEBw8eGB1FWAFHR0emTZtG7969GTNmjNFxsl35\\n8uU5depUhreX1R2zwe3btwkICOCHH36gZs2aRsexCnFxcbzwwgt2cfYlzCs1NZWbN2+SnJyMr6+v\\n0XGyxalTpzh37hwtWrSQ1R2NEBkZiaenJ8ePH5dSz4RTp05Rvnx5o2MIK+Ts7MyOHTto2LAhZ8+e\\nNTpOtihfvjxNmjTJ8PZS7Ga0ePFi2rRpw+XLl3F1dTU6jlXx8/Nj5MiRRscQVqp79+6MGzeORo0a\\nZWos2lqYTKZM3ciY5XnsSqkSwGLAB9DAXK31Z1k9rrX5+uuvef/999mxYwdFixY1Oo7VKVu2bJaf\\nGiPsW//+/XFxcSEqKornnnvO6Dhm5eDgQNGiRTM8zm6OM/Y0YITWuiJQB3hDKVXRDMe1Glprfv31\\nV37++Web+wuVU4YMGcKsWbOMjiEAliwBX19wcHj4+5IlRifKsF69etG+fXvmzJnD4cOHjY5jVplZ\\nTyrLxa61vqy1jnz0z3eBk4DdrLW5evVqTpw4wcyZM+WMMwsePHiAs7Oz0THEkiUQHAxxcaD1w9+D\\ng62q3AHy589Py5YtOXfunNFRzKZZs2YZ3tasY+xKKV+gOpDxmfRWLDw8nH79+pGenm50FKuXmpoq\\nxW4J3n0XEhP//Fpi4sPXrUinTp0YPXo07dq14969e0bHMYvp06dneFuzrRWjlMoN/AS8pbW+84Q/\\nDwaCAZtYJ+Xy5cu8/PLLzJ07lypVqhgdx+pVq1bNrh+qYDHi4zP3ugUbOnQoTk5ONrP0wLBhwzK8\\nrVnmsSulnIF1wGat9SdP294W5rGHh4ezZ88e3nrrLaOjCGE+vr4Ph1/+qlQpsNJhjfj4eDZs2MCA\\nAQOMjpIlAQEBREZG5sw8dvXwSctfAyczUurWTmvN0qVLqV69upS6GX3zzTesWLHC6Bjiww/B3f3P\\nr7m7P3zdSrm5uTFlyhRCQkKMjpIlycnJGd7WHGPs9YBXgSZKqcOPfrUyw3Et0scff8xHH30kt76b\\n2Y0bN9i9e7fRMcS//w1z5z48Q1fq4e9z5z583UoVKlSI1atX88Ybb3Do0CGj4zyzmzdvZnjbLI+x\\na633ACqrx7EGGzZs4JNPPiE0NBT3v57ViCx57rnn2LFjh9ExBDwscSsu8iepVq0ac+bMserVIC9d\\nupThB/PIgzYyYdeuXSxfvpwSJUoYHcXmlC9fnngrvEAnrEeHDh3QWrNo0SL+/e9/4+RkPfV35swZ\\njh8/nuHtreffzEAmk4mYmBimTZtmdBSb5e/vz9GjR42OIWyc1prFixdz48YNRowYYXScDNuxYwdh\\nYWEZ3l7WismABQsW0Lt3b4xYCdNeKKVYtmwZFy5cMDqKsGEODg7MmTOHKVOmEBMTY3ScDMvsInlS\\n7E9x+fJlxowZw+zZs3

In [268]:
repo_list[5].full_name

'ds-modules/NESTUD-190A'

In [269]:
filepaths[5]

[ContentFile(path=".gitignore"),
 ContentFile(path="LICENSE"),
 ContentFile(path="README.md"),
 ContentFile(path="Intro to Strings and Regex/Intro to Strings and Regex.ipynb"),
 ContentFile(path="Intro to Strings and Regex/appendix_37.png"),
 ContentFile(path="Intro to Strings and Regex/coffee_133_152.txt"),
 ContentFile(path="Intro to Strings and Regex/coffee_1_43.txt"),
 ContentFile(path="Intro to Strings and Regex/coffee_44_133.txt"),
 ContentFile(path="Intro to Strings and Regex/page_125.png"),
 ContentFile(path="Intro to Strings and Regex/page_5.png"),
 ContentFile(path="Intro to Strings and Regex/page_number.png"),
 ContentFile(path="More Strings and Regex/Grand Strategy of Phillip II Text.txt"),
 ContentFile(path="More Strings and Regex/LinssenCM25 adobe txt.txt"),
 ContentFile(path="More Strings and Regex/More Strings and Regex - BK.ipynb"),
 ContentFile(path="More Strings and Regex/feb16.zip"),
 ContentFile(path="More Strings and Regex/linsenn_to_page_69.txt"),
 ContentFile(path="More Strings and Regex/sidebyside.py"),
 ContentFile(path="Networks/Google Sheets.png"),
 ContentFile(path="Networks/IDing Nodes and Edges-checkpoint.ipynb"),
 ContentFile(path="Networks/WellonsG Graffiti mochicas in the Huaca Cao Viejo, El Brujo - Sheet1.csv"),
 ContentFile(path="Visualization/ArcGISLiveDemoInstructions.docx"),
 ContentFile(path="Visualization/Bokeh Time Series.ipynb"),
 ContentFile(path="Visualization/CTCPcc.csv"),
 ContentFile(path="Visualization/Graffiti.csv"),
 ContentFile(path="Visualization/Heat Maps and Trees.ipynb"),
 ContentFile(path="Visualization/Medici Box Plot.ipynb"),
 ContentFile(path="Visualization/Phillip II.csv"),
 ContentFile(path="Visualization/Spices.csv"),
 ContentFile(path="Visualization/TU 38 master - Sheet1.csv"),
 ContentFile(path="Visualization/Tree.ipynb"),
 ContentFile(path="Visualization/cultural_repatriation_medici_scandal_years.csv"),
 ContentFile(path="Visualization/cultural_repatriation_medici_scandal_years2.csv"),
 ContentFile(path="Visualization/google_sheets_coffee.png"),
 ContentFile(path="Visualization/google_sheets_spices.png"),
 ContentFile(path="Visualization/pubschls.csv"),
 ContentFile(path="Visualization/trees_and_heatmaps.zip"),
 ContentFile(path="digital-assyriology-review/Digital-Assyriology-Day-1.ipynb"),
 ContentFile(path="digital-assyriology-review/Digital-Assyriology-HW.ipynb"),
 ContentFile(path="digital-assyriology-review/Enmerkar.txt"),
 ContentFile(path="digital-assyriology/Digital-Assyriology-Day-1.ipynb"),
 ContentFile(path="digital-assyriology/Digital-Assyriology-HW.ipynb"),
 ContentFile(path="digital-assyriology/Enmerkar.txt"),
 ContentFile(path="foreign_languages/Sara_danish.ipynb"),
 ContentFile(path="foreign_languages/Skyggebilleder af en Reise til Harzen.txt"),
 ContentFile(path="foreign_languages/Tuesday_2_21.zip"),
 ContentFile(path="foreign_languages/anderson.py"),
 ContentFile(path="foreign_languages/linsenn_to_page_69.txt"),
 ContentFile(path="digital-assyriology-review/datascience/__init__.py"),
 ContentFile(path="digital-assyriology-review/datascience/formats.py"),
 ContentFile(path="digital-assyriology-review/datascience/maps.py"),
 ContentFile(path="digital-assyriology-review/datascience/predicates.py"),
 ContentFile(path="digital-assyriology-review/datascience/tables.py"),
 ContentFile(path="digital-assyriology-review/datascience/util.py"),
 ContentFile(path="digital-assyriology-review/datascience/version.py")]

In [380]:
notebook_contents = []
for i in range(len(ipynb_counts)):
    repo_contents = []
    if ipynb_counts[i] == 0:
        repo_contents.append([])
    else:
        for j in range(len(filepaths[i])):
            filepath = filepaths[i][j].path
            if 'ipynb' in filepath:
                if repo_list[i].get_contents(filepath).content == '':
                    print('content error: ', filepath)
                    repo_contents.append('')
                    continue
                try:
                    repo_contents.append(repo_list[i].get_contents(filepath).decoded_content.decode('utf-8'))
                except UnicodeDecodeError: 
                    repo_contents.append('')
                    print('Unicode Error', filepath)
                    continue
            else:
                repo_contents.append('')
    notebook_contents.append(repo_contents)

content error:  usage-analysis/Usage Analysis.ipynb
content error:  Lab07/staff.ipynb
content error:  IAS-150-notebook-sample.ipynb
content error:  IAS-150_notebook-playtest.ipynb

UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

In [367]:
abcd = ['a','b','c','d']
abcd = [[i] for i in abcd]
abcd

[['a'], ['b'], ['c'], ['d']]

In [373]:
for i in range(len(notebook_contents)):
    notebook_contents[i]  = [[j] for j in notebook_contents[i]]

In [374]:
notebook_contents[0]

[[''],
 [''],
 [''],
 [''],
 ['import json\nimport autopep8\nimport sys\nimport re\n\nfile_path = sys.argv[1]\nnotebook = json.load(open(file_path, \'r\'))\n\nfor c in notebook[\'cells\']:\n    if c[\'cell_type\'] == \'code\':\n        cell_code = \'\'.join(c[\'source\'])\n        pep8_code = autopep8.fix_code(cell_code)\n        pep8_cell = re.split(r\'(\\n)\', pep8_code)\n        pep8_cell = [x for x in pep8_cell if len(x) > 0]\n\n        if len(pep8_cell) > 0 and pep8_cell[-1] == "\\n":\n            pep8_cell = pep8_cell[:-1]\n\n        c[\'source\'] = pep8_cell\n\nnew_file_path = file_path[:-6] + \'-PEP8.ipynb\'\njson.dump(notebook, open(new_file_path, "w"))\n'],
 [''],
 [''],
 [''],
 [''],
 ['{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "### Calling\\n",\n    "After you define a function, it\'s time to use it. This is known as _calling_ a function. \\n",\n    "\\n",\n    "To call a function, simply write the name of the function with your input variable in brackets (argument).\\n"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": 1,\n   "metadata": {\n    "collapsed": false\n   },\n   "outputs": [\n    {\n     "ename": "SyntaxError",\n     "evalue": "invalid syntax (<ipython-input-1-0919a320d65c>, line 2)",\n     "output_type": "error",\n     "traceback": [\n      "\\u001b[0;36m  File \\u001b[0;32m\\"<ipython-input-1-0919a320d65c>\\"\\u001b[0;36m, line \\u001b[0;32m2\\u001b[0m\\n\\u001b[0;31m    def #name(argument):\\u001b[0m\\n\\u001b[0m                        ^\\u001b[0m\\n\\u001b[0;31mSyntaxError\\u001b[0m\\u001b[0;31m:\\u001b[0m invalid syntax\\n"\n     ]\n    }\n   ],\n   "source": [\n    "# Complete this function\\n",\n    "def #name(argument):\\n",\n    "    return # function must return a value\\n",\n    "\\n",\n    "# Calling our function below...\\n",\n    "my_first_function(name)"\n   ]\n  },\n  {\n   "cell_type": "code",\n   "execution_count": null,\n   "metadata": {\n    "collapsed": true\n   },\n   "outputs": [],\n   "source": []\n  }\n ],\n "metadata": {\n  "kernelspec": {\n   "display_name": "Python [conda root]",\n   "language": "python",\n   "name": "conda-root-py"\n  },\n  "language_info": {\n   "codemirror_mode": {\n    "name": "ipython",\n    "version": 3\n   },\n   "file_extension": ".py",\n   "mimetype": "text/x-python",\n   "name": "python",\n   "nbconvert_exporter": "python",\n   "pygments_lexer": "ipython3",\n   "version": "3.5.2"\n  }\n },\n "nbformat": 4,\n "nbformat_minor": 1\n}\n'],

In [378]:
with open('contents.txt', 'w') as filehandle:
    for i in notebook_contents:
        filehandle.write(f'{i}\n')

In [375]:
import csv

with open("contents.csv", "w") as f:
    wr = csv.writer(f)
    wr.writerows([notebook_contents])

In [376]:
len(notebook_contents[21])

141